import { deliveryZones } from "@/lib/constants";
import { slugify } from "@/lib/utils";

export type PaymentMethod = "pix" | "cartao" | "boleto";
export type SalesChannel = "site" | "mercadolivre" | "shopee" | "whatsapp";
export type Product = {
  id: string;
  sku: string;
  name: string;
  category: string;
  subcategory: string;
  theme: string;
  collection: string;
  colors: string[];
  grams: number;
  hours: number;
  complexity: number;
  featured: boolean;
  description: string;
  tags: string[];
  pricePix: number;
  priceCard: number;
  marketplaceSuggested: number;
  productionWindow: string;
  imageHint: string;
  image?: string;
  images?: string[];
  material: string;
  finish: string;
  status: "Pronta entrega" | "Sob encomenda";
  stock: number;
  dimensions: string;
  customizable: boolean;
  readyToShip?: boolean;
};

const filamentCostPerGram = 0.11;

function toPriceEnding(value: number) {
  const base = Math.max(9, Math.ceil(value));
  return Number((base - 0.1).toFixed(2));
}

export function calculateBaseCost(grams: number, hours: number, complexity = 1) {
  const material = grams * filamentCostPerGram;
  const machine = Math.max(2, hours * 2.75);
  const acabamento = Math.max(1.5, complexity * 2.2);
  return Number((material + machine + acabamento).toFixed(2));
}

export function calculateSalePrice(
  grams: number,
  hours: number,
  complexity = 1,
  paymentMethod: PaymentMethod = "pix",
  channel: SalesChannel = "site"
) {
  let price = calculateBaseCost(grams, hours, complexity) * 1.95;
  if (paymentMethod === "cartao") price *= 1.12;
  if (paymentMethod === "boleto") price *= 1.08;
  if (channel === "mercadolivre") price *= 1.15;
  if (channel === "shopee") price *= 1.12;
  return toPriceEnding(price);
}

const curatedCatalog: Product[] = [
  // Geek & Colecionáveis Autorais (12 produtos)
  {
    id: "mdh-001",
    sku: "MDH-0001",
    name: "Hello Kitty Chibi Premium",
    category: "Geek & Colecionáveis",
    subcategory: "Chibi",
    theme: "Anime",
    collection: "Mais vendidos",
    colors: ["Rosa", "Branco"],
    grams: 32,
    hours: 1.9,
    complexity: 1.27,
    featured: true,
    description: "Peça compacta e marcante para colecionar, decorar setup ou presentear. Produzida em PLA Silk com acabamento premium.",
    tags: ["kawaii", "presente", "pronta entrega"],
    pricePix: 29.9,
    priceCard: 34.9,
    marketplaceSuggested: 39.09,
    productionWindow: "24h a 48h",
    imageHint: "Hello Kitty Chibi Premium",
    image: "/assets/images/products/product-01.jpg",
    images: ["/assets/images/products/product-01.jpg"],
    material: "PLA Silk",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 14,
    dimensions: "8x6x10cm",
    customizable: true,
    readyToShip: false,
  },
  {
    id: "mdh-002",
    sku: "MDH-0002",
    name: "Mascote Kawaii Desk Buddy",
    category: "Geek & Colecionáveis",
    subcategory: "Mascote",
    theme: "Anime",
    collection: "Pronta entrega",
    colors: ["Amarelo", "Branco", "Azul"],
    grams: 28,
    hours: 1.7,
    complexity: 1.24,
    featured: false,
    description: "Peça compacta e marcante para colecionar, decorar setup ou presentear.",
    tags: ["chibi", "mesa", "colecionável"],
    pricePix: 26.9,
    priceCard: 31.9,
    marketplaceSuggested: 35.73,
    productionWindow: "24h a 48h",
    imageHint: "Mascote Kawaii Desk Buddy",
    image: "/assets/images/products/product-02.jpg",
    images: ["/assets/images/products/product-02.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Pronta entrega",
    stock: 18,
    dimensions: "7x6x9cm",
    customizable: true,
    readyToShip: true,
  },
  {
    id: "mdh-003",
    sku: "MDH-0003",
    name: "Monstro Elétrico Pocket Mini",
    category: "Geek & Colecionáveis",
    subcategory: "Colecionável",
    theme: "Geek",
    collection: "Mais vendidos",
    colors: ["Amarelo", "Preto"],
    grams: 34,
    hours: 2.1,
    complexity: 1.29,
    featured: true,
    description: "Peça compacta e marcante para colecionar, decorar setup ou presentear.",
    tags: ["pocket", "geek", "presente"],
    pricePix: 34.9,
    priceCard: 39.9,
    marketplaceSuggested: 44.69,
    productionWindow: "24h a 48h",
    imageHint: "Monstro Elétrico Pocket Mini",
    image: "/assets/images/products/product-03.jpg",
    images: ["/assets/images/products/product-03.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 10,
    dimensions: "8x6x11cm",
    customizable: false,
    readyToShip: false,
  },
  {
    id: "mdh-004",
    sku: "MDH-0004",
    name: "Espiã Mirim Chibi",
    category: "Geek & Colecionáveis",
    subcategory: "Chibi",
    theme: "Anime",
    collection: "Pronta entrega",
    colors: ["Rosa", "Preto", "Dourado"],
    grams: 38,
    hours: 2.4,
    complexity: 1.33,
    featured: true,
    description: "Peça compacta e marcante para colecionar, decorar setup ou presentear.",
    tags: ["anime", "fofo", "coleção"],
    pricePix: 33.9,
    priceCard: 38.9,
    marketplaceSuggested: 43.57,
    productionWindow: "24h a 48h",
    imageHint: "Espiã Mirim Chibi",
    image: "/assets/images/products/product-04.jpg",
    images: ["/assets/images/products/product-04.jpg"],
    material: "PLA Silk",
    finish: "Premium",
    status: "Pronta entrega",
    stock: 9,
    dimensions: "8x7x11cm",
    customizable: false,
    readyToShip: true,
  },
  {
    id: "mdh-005",
    sku: "MDH-0005",
    name: "Mascote Serra Articulado",
    category: "Geek & Colecionáveis",
    subcategory: "Articulado",
    theme: "Anime",
    collection: "Sob encomenda",
    colors: ["Laranja", "Branco"],
    grams: 41,
    hours: 2.8,
    complexity: 1.38,
    featured: false,
    description: "Peça compacta e marcante para colecionar, decorar setup ou presentear.",
    tags: ["articulado", "anime", "display"],
    pricePix: 31.9,
    priceCard: 36.9,
    marketplaceSuggested: 41.33,
    productionWindow: "3 a 5 dias",
    imageHint: "Mascote Serra Articulado",
    image: "/assets/images/products/product-05.jpg",
    images: ["/assets/images/products/product-05.jpg"],
    material: "PLA Premium",
    finish: "Texturizado",
    status: "Sob encomenda",
    stock: 7,
    dimensions: "10x7x8cm",
    customizable: false,
    readyToShip: false,
  },
  {
    id: "mdh-006",
    sku: "MDH-0006",
    name: "Tripulante Crewmate Neon",
    category: "Geek & Colecionáveis",
    subcategory: "Miniatura",
    theme: "Game",
    collection: "Pronta entrega",
    colors: ["Vermelho", "Azul", "Preto"],
    grams: 24,
    hours: 1.2,
    complexity: 1.18,
    featured: false,
    description: "Peça compacta e marcante para colecionar, decorar setup ou presentear.",
    tags: ["game", "colecionável", "mesa"],
    pricePix: 22.9,
    priceCard: 26.9,
    marketplaceSuggested: 30.13,
    productionWindow: "24h a 48h",
    imageHint: "Tripulante Crewmate Neon",
    image: "/assets/images/products/product-06.jpg",
    images: ["/assets/images/products/product-06.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Pronta entrega",
    stock: 20,
    dimensions: "6x5x8cm",
    customizable: true,
    readyToShip: true,
  },
  {
    id: "mdh-007",
    sku: "MDH-0007",
    name: "Esfera Monstro de Bolso",
    category: "Geek & Colecionáveis",
    subcategory: "Acessório",
    theme: "Geek",
    collection: "Mais vendidos",
    colors: ["Vermelho", "Branco", "Preto"],
    grams: 22,
    hours: 1.1,
    complexity: 1.17,
    featured: true,
    description: "Peça compacta e marcante para colecionar, decorar setup ou presentear.",
    tags: ["coleção", "presente", "geek"],
    pricePix: 19.9,
    priceCard: 23.9,
    marketplaceSuggested: 26.77,
    productionWindow: "24h a 48h",
    imageHint: "Esfera Monstro de Bolso",
    image: "/assets/images/products/product-07.jpg",
    images: ["/assets/images/products/product-07.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 15,
    dimensions: "5x5x5cm",
    customizable: true,
    readyToShip: false,
  },
  {
    id: "mdh-008",
    sku: "MDH-0008",
    name: "Pokémon Pikachu Mini",
    category: "Geek & Colecionáveis",
    subcategory: "Miniatura",
    theme: "Game",
    collection: "Mais vendidos",
    colors: ["Amarelo", "Preto"],
    grams: 30,
    hours: 1.8,
    complexity: 1.25,
    featured: true,
    description: "Peça compacta e marcante para colecionar, decorar setup ou presentear.",
    tags: ["pokemon", "pikachu", "colecionável"],
    pricePix: 28.9,
    priceCard: 33.9,
    marketplaceSuggested: 38.13,
    productionWindow: "24h a 48h",
    imageHint: "Pokémon Pikachu Mini",
    image: "/assets/images/products/product-08.jpg",
    images: ["/assets/images/products/product-08.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 12,
    dimensions: "7x6x9cm",
    customizable: false,
    readyToShip: false,
  },
  {
    id: "mdh-009",
    sku: "MDH-0009",
    name: "Spy x Family Anya Chibi",
    category: "Geek & Colecionáveis",
    subcategory: "Chibi",
    theme: "Anime",
    collection: "Mais vendidos",
    colors: ["Rosa", "Branco"],
    grams: 35,
    hours: 2.2,
    complexity: 1.30,
    featured: true,
    description: "Peça compacta e marcante para colecionar, decorar setup ou presentear.",
    tags: ["spy x family", "anya", "anime"],
    pricePix: 32.9,
    priceCard: 37.9,
    marketplaceSuggested: 42.13,
    productionWindow: "24h a 48h",
    imageHint: "Spy x Family Anya Chibi",
    image: "/assets/images/products/product-09.jpg",
    images: ["/assets/images/products/product-09.jpg"],
    material: "PLA Silk",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 10,
    dimensions: "8x6x10cm",
    customizable: false,
    readyToShip: false,
  },
  {
    id: "mdh-010",
    sku: "MDH-0010",
    name: "Chainsaw Man Pochita",
    category: "Geek & Colecionáveis",
    subcategory: "Colecionável",
    theme: "Anime",
    collection: "Mais vendidos",
    colors: ["Vermelho", "Preto"],
    grams: 40,
    hours: 2.5,
    complexity: 1.35,
    featured: true,
    description: "Peça compacta e marcante para colecionar, decorar setup ou presentear.",
    tags: ["chainsaw man", "pochita", "anime"],
    pricePix: 35.9,
    priceCard: 40.9,
    marketplaceSuggested: 45.13,
    productionWindow: "24h a 48h",
    imageHint: "Chainsaw Man Pochita",
    image: "/assets/images/products/product-10.jpg",
    images: ["/assets/images/products/product-10.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 8,
    dimensions: "9x7x8cm",
    customizable: false,
    readyToShip: false,
  },
  {
    id: "mdh-011",
    sku: "MDH-0011",
    name: "Minecraft Steve Figurine",
    category: "Geek & Colecionáveis",
    subcategory: "Miniatura",
    theme: "Game",
    collection: "Pronta entrega",
    colors: ["Azul", "Preto"],
    grams: 45,
    hours: 2.8,
    complexity: 1.40,
    featured: false,
    description: "Peça compacta e marcante para colecionar, decorar setup ou presentear.",
    tags: ["minecraft", "steve", "game"],
    pricePix: 38.9,
    priceCard: 43.9,
    marketplaceSuggested: 48.13,
    productionWindow: "24h a 48h",
    imageHint: "Minecraft Steve Figurine",
    image: "/assets/images/products/product-11.jpg",
    images: ["/assets/images/products/product-11.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Pronta entrega",
    stock: 15,
    dimensions: "10x8x12cm",
    customizable: true,
    readyToShip: true,
  },
  {
    id: "mdh-012",
    sku: "MDH-0012",
    name: "Creeper Minecraft",
    category: "Geek & Colecionáveis",
    subcategory: "Miniatura",
    theme: "Game",
    collection: "Pronta entrega",
    colors: ["Verde", "Preto"],
    grams: 42,
    hours: 2.6,
    complexity: 1.38,
    featured: false,
    description: "Peça compacta e marcante para colecionar, decorar setup ou presentear.",
    tags: ["minecraft", "creeper", "game"],
    pricePix: 36.9,
    priceCard: 41.9,
    marketplaceSuggested: 46.13,
    productionWindow: "24h a 48h",
    imageHint: "Creeper Minecraft",
    image: "/assets/images/products/product-12.jpg",
    images: ["/assets/images/products/product-12.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Pronta entrega",
    stock: 18,
    dimensions: "9x7x10cm",
    customizable: false,
    readyToShip: true,
  },
  // Setup & Organização (12 produtos)
  {
    id: "mdh-013",
    sku: "MDH-0013",
    name: "Suporte para Fone Headphone",
    category: "Setup & Organização",
    subcategory: "Suporte",
    theme: "Setup",
    collection: "Mais vendidos",
    colors: ["Preto", "Branco"],
    grams: 80,
    hours: 3.2,
    complexity: 1.35,
    featured: true,
    description: "Suporte funcional para organizar seu setup de trabalho ou gaming.",
    tags: ["suporte", "fone", "setup"],
    pricePix: 55.9,
    priceCard: 60.9,
    marketplaceSuggested: 65.13,
    productionWindow: "3 a 5 dias",
    imageHint: "Suporte para Fone Headphone",
    image: "/assets/images/products/product-13.jpg",
    images: ["/assets/images/products/product-13.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 10,
    dimensions: "15x10x8cm",
    customizable: true,
    readyToShip: false,
  },
  {
    id: "mdh-014",
    sku: "MDH-0014",
    name: "Organizador de Cabos",
    category: "Setup & Organização",
    subcategory: "Organizador",
    theme: "Setup",
    collection: "Pronta entrega",
    colors: ["Preto", "Branco"],
    grams: 25,
    hours: 1.5,
    complexity: 1.20,
    featured: false,
    description: "Organizador prático para manter seus cabos organizados.",
    tags: ["organizador", "cabos", "setup"],
    pricePix: 18.9,
    priceCard: 22.9,
    marketplaceSuggested: 25.13,
    productionWindow: "24h a 48h",
    imageHint: "Organizador de Cabos",
    image: "/assets/images/products/product-14.jpg",
    images: ["/assets/images/products/product-14.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Pronta entrega",
    stock: 25,
    dimensions: "10x5x5cm",
    customizable: false,
    readyToShip: true,
  },
  {
    id: "mdh-015",
    sku: "MDH-0015",
    name: "Suporte para Celular",
    category: "Setup & Organização",
    subcategory: "Suporte",
    theme: "Setup",
    collection: "Pronta entrega",
    colors: ["Preto", "Branco"],
    grams: 30,
    hours: 1.8,
    complexity: 1.25,
    featured: false,
    description: "Suporte ajustável para celular em mesa ou parede.",
    tags: ["suporte", "celular", "setup"],
    pricePix: 22.9,
    priceCard: 26.9,
    marketplaceSuggested: 29.13,
    productionWindow: "24h a 48h",
    imageHint: "Suporte para Celular",
    image: "/assets/images/products/product-15.jpg",
    images: ["/assets/images/products/product-15.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Pronta entrega",
    stock: 20,
    dimensions: "8x6x10cm",
    customizable: true,
    readyToShip: true,
  },
  {
    id: "mdh-016",
    sku: "MDH-0016",
    name: "Chaveiro Personalizado",
    category: "Setup & Organização",
    subcategory: "Acessório",
    theme: "Personalizado",
    collection: "Mais vendidos",
    colors: ["Preto", "Branco"],
    grams: 15,
    hours: 0.8,
    complexity: 1.10,
    featured: true,
    description: "Chaveiro personalizado com seu nome ou logo.",
    tags: ["chaveiro", "personalizado", "acessório"],
    pricePix: 12.9,
    priceCard: 15.9,
    marketplaceSuggested: 18.13,
    productionWindow: "24h a 48h",
    imageHint: "Chaveiro Personalizado",
    image: "/assets/images/products/product-16.jpg",
    images: ["/assets/images/products/product-16.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 30,
    dimensions: "5x3x1cm",
    customizable: true,
    readyToShip: false,
  },
  {
    id: "mdh-017",
    sku: "MDH-0017",
    name: "Suporte para Controle PS5",
    category: "Setup & Organização",
    subcategory: "Suporte",
    theme: "Gaming",
    collection: "Mais vendidos",
    colors: ["Preto", "Branco"],
    grams: 60,
    hours: 2.8,
    complexity: 1.30,
    featured: true,
    description: "Suporte para controle PS5 com carregamento integrado.",
    tags: ["suporte", "ps5", "gaming"],
    pricePix: 45.9,
    priceCard: 50.9,
    marketplaceSuggested: 55.13,
    productionWindow: "3 a 5 dias",
    imageHint: "Suporte para Controle PS5",
    image: "/assets/images/products/product-17.jpg",
    images: ["/assets/images/products/product-17.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 12,
    dimensions: "12x8x6cm",
    customizable: false,
    readyToShip: false,
  },
  {
    id: "mdh-018",
    sku: "MDH-0018",
    name: "Suporte para Controle Xbox",
    category: "Setup & Organização",
    subcategory: "Suporte",
    theme: "Gaming",
    collection: "Mais vendidos",
    colors: ["Verde", "Preto"],
    grams: 58,
    hours: 2.7,
    complexity: 1.28,
    featured: true,
    description: "Suporte para controle Xbox com design ergonômico.",
    tags: ["suporte", "xbox", "gaming"],
    pricePix: 43.9,
    priceCard: 48.9,
    marketplaceSuggested: 53.13,
    productionWindow: "3 a 5 dias",
    imageHint: "Suporte para Controle Xbox",
    image: "/assets/images/products/product-18.jpg",
    images: ["/assets/images/products/product-18.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 14,
    dimensions: "12x8x6cm",
    customizable: false,
    readyToShip: false,
  },
  {
    id: "mdh-019",
    sku: "MDH-0019",
    name: "Porta-Copos Geek",
    category: "Setup & Organização",
    subcategory: "Acessório",
    theme: "Geek",
    collection: "Pronta entrega",
    colors: ["Preto", "Branco"],
    grams: 35,
    hours: 2.0,
    complexity: 1.22,
    featured: false,
    description: "Porta-copos com design geek para sua mesa.",
    tags: ["porta-copos", "geek", "mesa"],
    pricePix: 25.9,
    priceCard: 29.9,
    marketplaceSuggested: 32.13,
    productionWindow: "24h a 48h",
    imageHint: "Porta-Copos Geek",
    image: "/assets/images/products/product-19.jpg",
    images: ["/assets/images/products/product-19.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Pronta entrega",
    stock: 22,
    dimensions: "8x8x5cm",
    customizable: true,
    readyToShip: true,
  },
  {
    id: "mdh-020",
    sku: "MDH-0020",
    name: "Imã de Geladeira",
    category: "Setup & Organização",
    subcategory: "Acessório",
    theme: "Casa",
    collection: "Pronta entrega",
    colors: ["Colorido"],
    grams: 20,
    hours: 1.2,
    complexity: 1.15,
    featured: false,
    description: "Imã de geladeira personalizado com design 3D.",
    tags: ["imã", "geladeira", "personalizado"],
    pricePix: 15.9,
    priceCard: 18.9,
    marketplaceSuggested: 21.13,
    productionWindow: "24h a 48h",
    imageHint: "Imã de Geladeira",
    image: "/assets/images/products/product-20.jpg",
    images: ["/assets/images/products/product-20.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Pronta entrega",
    stock: 28,
    dimensions: "6x4x1cm",
    customizable: true,
    readyToShip: true,
  },
  {
    id: "mdh-021",
    sku: "MDH-0021",
    name: "Suporte para Mouse",
    category: "Setup & Organização",
    subcategory: "Suporte",
    theme: "Setup",
    collection: "Pronta entrega",
    colors: ["Preto", "Branco"],
    grams: 40,
    hours: 2.2,
    complexity: 1.25,
    featured: false,
    description: "Suporte ergonômico para mouse de computador.",
    tags: ["suporte", "mouse", "setup"],
    pricePix: 28.9,
    priceCard: 32.9,
    marketplaceSuggested: 35.13,
    productionWindow: "24h a 48h",
    imageHint: "Suporte para Mouse",
    image: "/assets/images/products/product-21.jpg",
    images: ["/assets/images/products/product-21.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Pronta entrega",
    stock: 16,
    dimensions: "10x8x3cm",
    customizable: false,
    readyToShip: true,
  },
  {
    id: "mdh-022",
    sku: "MDH-0022",
    name: "Organizador de Canetas",
    category: "Setup & Organização",
    subcategory: "Organizador",
    theme: "Setup",
    collection: "Pronta entrega",
    colors: ["Preto", "Branco"],
    grams: 50,
    hours: 2.5,
    complexity: 1.28,
    featured: false,
    description: "Organizador para canetas e pequenos objetos.",
    tags: ["organizador", "canetas", "mesa"],
    pricePix: 32.9,
    priceCard: 36.9,
    marketplaceSuggested: 39.13,
    productionWindow: "24h a 48h",
    imageHint: "Organizador de Canetas",
    image: "/assets/images/products/product-22.jpg",
    images: ["/assets/images/products/product-22.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Pronta entrega",
    stock: 18,
    dimensions: "12x8x5cm",
    customizable: true,
    readyToShip: true,
  },
  {
    id: "mdh-023",
    sku: "MDH-0023",
    name: "Suporte para Teclado",
    category: "Setup & Organização",
    subcategory: "Suporte",
    theme: "Setup",
    collection: "Sob encomenda",
    colors: ["Preto", "Branco"],
    grams: 70,
    hours: 3.0,
    complexity: 1.35,
    featured: false,
    description: "Suporte ajustável para teclado mecânico.",
    tags: ["suporte", "teclado", "setup"],
    pricePix: 48.9,
    priceCard: 53.9,
    marketplaceSuggested: 56.13,
    productionWindow: "3 a 5 dias",
    imageHint: "Suporte para Teclado",
    image: "/assets/images/products/product-23.jpg",
    images: ["/assets/images/products/product-23.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 8,
    dimensions: "40x15x5cm",
    customizable: true,
    readyToShip: false,
  },
  {
    id: "mdh-024",
    sku: "MDH-0024",
    name: "Gancho para Parede",
    category: "Setup & Organização",
    subcategory: "Acessório",
    theme: "Casa",
    collection: "Pronta entrega",
    colors: ["Preto", "Branco"],
    grams: 25,
    hours: 1.5,
    complexity: 1.20,
    featured: false,
    description: "Gancho decorativo para parede com design 3D.",
    tags: ["gancho", "parede", "decoração"],
    pricePix: 19.9,
    priceCard: 23.9,
    marketplaceSuggested: 26.13,
    productionWindow: "24h a 48h",
    imageHint: "Gancho para Parede",
    image: "/assets/images/products/product-24.jpg",
    images: ["/assets/images/products/product-24.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Pronta entrega",
    stock: 24,
    dimensions: "8x5x3cm",
    customizable: true,
    readyToShip: true,
  },
  // Casa & Decoração (12 produtos)
  {
    id: "mdh-025",
    sku: "MDH-0025",
    name: "Vaso Geométrico",
    category: "Casa & Decoração",
    subcategory: "Vaso",
    theme: "Decoração",
    collection: "Mais vendidos",
    colors: ["Preto", "Branco"],
    grams: 120,
    hours: 4.0,
    complexity: 1.45,
    featured: true,
    description: "Vaso decorativo com design geométrico moderno.",
    tags: ["vaso", "geométrico", "decoração"],
    pricePix: 75.9,
    priceCard: 80.9,
    marketplaceSuggested: 85.13,
    productionWindow: "3 a 5 dias",
    imageHint: "Vaso Geométrico",
    image: "/assets/images/products/product-25.jpg",
    images: ["/assets/images/products/product-25.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 6,
    dimensions: "15x15x20cm",
    customizable: true,
    readyToShip: false,
  },
  {
    id: "mdh-026",
    sku: "MDH-0026",
    name: "Pokébola",
    category: "Casa & Decoração",
    subcategory: "Colecionável",
    theme: "Game",
    collection: "Pronta entrega",
    colors: ["Vermelho", "Branco", "Preto"],
    grams: 30,
    hours: 1.8,
    complexity: 1.25,
    featured: false,
    description: "Pokébola decorativa para fãs de Pokémon.",
    tags: ["pokébola", "pokemon", "decoração"],
    pricePix: 22.9,
    priceCard: 26.9,
    marketplaceSuggested: 29.13,
    productionWindow: "24h a 48h",
    imageHint: "Pokébola",
    image: "/assets/images/products/product-26.jpg",
    images: ["/assets/images/products/product-26.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Pronta entrega",
    stock: 20,
    dimensions: "8x8x8cm",
    customizable: false,
    readyToShip: true,
  },
  {
    id: "mdh-027",
    sku: "MDH-0027",
    name: "Busto Colecionável Anime",
    category: "Casa & Decoração",
    subcategory: "Busto",
    theme: "Anime",
    collection: "Mais vendidos",
    colors: ["Preto", "Branco"],
    grams: 150,
    hours: 5.0,
    complexity: 1.50,
    featured: true,
    description: "Busto detalhado de personagem anime para colecionadores.",
    tags: ["busto", "anime", "colecionável"],
    pricePix: 95.9,
    priceCard: 100.9,
    marketplaceSuggested: 105.13,
    productionWindow: "5 a 7 dias",
    imageHint: "Busto Colecionável Anime",
    image: "/assets/images/products/product-27.jpg",
    images: ["/assets/images/products/product-27.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 4,
    dimensions: "20x15x25cm",
    customizable: false,
    readyToShip: false,
  },
  {
    id: "mdh-028",
    sku: "MDH-0028",
    name: "Luminária LED Personalizada",
    category: "Casa & Decoração",
    subcategory: "Luminária",
    theme: "Personalizado",
    collection: "Sob encomenda",
    colors: ["Branco"],
    grams: 200,
    hours: 6.0,
    complexity: 1.60,
    featured: true,
    description: "Luminária LED com design personalizado.",
    tags: ["luminária", "led", "personalizado"],
    pricePix: 125.9,
    priceCard: 130.9,
    marketplaceSuggested: 135.13,
    productionWindow: "5 a 7 dias",
    imageHint: "Luminária LED Personalizada",
    image: "/assets/images/products/product-28.jpg",
    images: ["/assets/images/products/product-28.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 2,
    dimensions: "25x20x30cm",
    customizable: true,
    readyToShip: false,
  },
  {
    id: "mdh-029",
    sku: "MDH-0029",
    name: "Foto Litofania",
    category: "Casa & Decoração",
    subcategory: "Foto",
    theme: "Personalizado",
    collection: "Sob encomenda",
    colors: ["Branco"],
    grams: 180,
    hours: 5.5,
    complexity: 1.55,
    featured: true,
    description: "Foto em litofania 3D com iluminação traseira.",
    tags: ["foto", "litofania", "personalizado"],
    pricePix: 110.9,
    priceCard: 115.9,
    marketplaceSuggested: 120.13,
    productionWindow: "5 a 7 dias",
    imageHint: "Foto Litofania",
    image: "/assets/images/products/product-29.jpg",
    images: ["/assets/images/products/product-29.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 3,
    dimensions: "20x15x5cm",
    customizable: true,
    readyToShip: false,
  },
  {
    id: "mdh-030",
    sku: "MDH-0030",
    name: "Quadro Decorativo",
    category: "Casa & Decoração",
    subcategory: "Quadro",
    theme: "Decoração",
    collection: "Pronta entrega",
    colors: ["Preto", "Branco"],
    grams: 100,
    hours: 3.5,
    complexity: 1.40,
    featured: false,
    description: "Quadro decorativo com design abstrato.",
    tags: ["quadro", "decorativo", "parede"],
    pricePix: 65.9,
    priceCard: 70.9,
    marketplaceSuggested: 75.13,
    productionWindow: "3 a 5 dias",
    imageHint: "Quadro Decorativo",
    image: "/assets/images/products/product-30.jpg",
    images: ["/assets/images/products/product-30.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Pronta entrega",
    stock: 10,
    dimensions: "30x20x3cm",
    customizable: true,
    readyToShip: true,
  },
  {
    id: "mdh-031",
    sku: "MDH-0031",
    name: "Escultura Abstrata",
    category: "Casa & Decoração",
    subcategory: "Escultura",
    theme: "Arte",
    collection: "Sob encomenda",
    colors: ["Preto", "Branco"],
    grams: 250,
    hours: 7.0,
    complexity: 1.70,
    featured: false,
    description: "Escultura abstrata para decoração moderna.",
    tags: ["escultura", "abstrata", "arte"],
    pricePix: 155.9,
    priceCard: 160.9,
    marketplaceSuggested: 165.13,
    productionWindow: "7 a 10 dias",
    imageHint: "Escultura Abstrata",
    image: "/assets/images/products/product-31.jpg",
    images: ["/assets/images/products/product-31.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 1,
    dimensions: "25x20x35cm",
    customizable: true,
    readyToShip: false,
  },
  {
    id: "mdh-032",
    sku: "MDH-0032",
    name: "Porta-Velhas",
    category: "Casa & Decoração",
    subcategory: "Acessório",
    theme: "Casa",
    collection: "Pronta entrega",
    colors: ["Preto", "Branco"],
    grams: 40,
    hours: 2.2,
    complexity: 1.25,
    featured: false,
    description: "Porta-velas decorativo com design elegante.",
    tags: ["porta-velas", "decoração", "casa"],
    pricePix: 28.9,
    priceCard: 32.9,
    marketplaceSuggested: 35.13,
    productionWindow: "24h a 48h",
    imageHint: "Porta-Velhas",
    image: "/assets/images/products/product-32.jpg",
    images: ["/assets/images/products/product-32.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Pronta entrega",
    stock: 15,
    dimensions: "10x10x8cm",
    customizable: false,
    readyToShip: true,
  },
  {
    id: "mdh-033",
    sku: "MDH-0033",
    name: "Relógio de Parede",
    category: "Casa & Decoração",
    subcategory: "Relógio",
    theme: "Casa",
    collection: "Sob encomenda",
    colors: ["Preto", "Branco"],
    grams: 80,
    hours: 3.2,
    complexity: 1.35,
    featured: false,
    description: "Relógio de parede com design 3D único.",
    tags: ["relógio", "parede", "decoração"],
    pricePix: 55.9,
    priceCard: 60.9,
    marketplaceSuggested: 65.13,
    productionWindow: "3 a 5 dias",
    imageHint: "Relógio de Parede",
    image: "/assets/images/products/product-33.jpg",
    images: ["/assets/images/products/product-33.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 5,
    dimensions: "25x5x25cm",
    customizable: true,
    readyToShip: false,
  },
  {
    id: "mdh-034",
    sku: "MDH-0034",
    name: "Jarro Decorativo",
    category: "Casa & Decoração",
    subcategory: "Jarro",
    theme: "Casa",
    collection: "Pronta entrega",
    colors: ["Preto", "Branco"],
    grams: 90,
    hours: 3.5,
    complexity: 1.40,
    featured: false,
    description: "Jarro decorativo para mesa ou prateleira.",
    tags: ["jarro", "decorativo", "mesa"],
    pricePix: 58.9,
    priceCard: 63.9,
    marketplaceSuggested: 68.13,
    productionWindow: "3 a 5 dias",
    imageHint: "Jarro Decorativo",
    image: "/assets/images/products/product-34.jpg",
    images: ["/assets/images/products/product-34.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Pronta entrega",
    stock: 12,
    dimensions: "12x12x18cm",
    customizable: true,
    readyToShip: true,
  },
  {
    id: "mdh-035",
    sku: "MDH-0035",
    name: "Prateleira Suspensa",
    category: "Casa & Decoração",
    subcategory: "Prateleira",
    theme: "Casa",
    collection: "Sob encomenda",
    colors: ["Preto", "Branco"],
    grams: 120,
    hours: 4.0,
    complexity: 1.45,
    featured: false,
    description: "Prateleira suspensa com design moderno.",
    tags: ["prateleira", "suspensa", "decoração"],
    pricePix: 78.9,
    priceCard: 83.9,
    marketplaceSuggested: 88.13,
    productionWindow: "3 a 5 dias",
    imageHint: "Prateleira Suspensa",
    image: "/assets/images/products/product-35.jpg",
    images: ["/assets/images/products/product-35.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 7,
    dimensions: "30x10x5cm",
    customizable: true,
    readyToShip: false,
  },
  {
    id: "mdh-036",
    sku: "MDH-0036",
    name: "Espelho Decorativo",
    category: "Casa & Decoração",
    subcategory: "Espelho",
    theme: "Casa",
    collection: "Sob encomenda",
    colors: ["Preto", "Branco"],
    grams: 150,
    hours: 5.0,
    complexity: 1.50,
    featured: false,
    description: "Espelho decorativo com moldura 3D.",
    tags: ["espelho", "decorativo", "parede"],
    pricePix: 95.9,
    priceCard: 100.9,
    marketplaceSuggested: 105.13,
    productionWindow: "5 a 7 dias",
    imageHint: "Espelho Decorativo",
    image: "/assets/images/products/product-36.jpg",
    images: ["/assets/images/products/product-36.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 3,
    dimensions: "25x20x3cm",
    customizable: true,
    readyToShip: false,
  },
  // Presentes Criativos (12 produtos)
  {
    id: "mdh-037",
    sku: "MDH-0037",
    name: "Chaveiro Nome Dupla Face",
    category: "Presentes Criativos",
    subcategory: "Chaveiro",
    theme: "Personalizado",
    collection: "Mais vendidos",
    colors: ["Preto", "Branco"],
    grams: 25,
    hours: 1.5,
    complexity: 1.20,
    featured: true,
    description: "Chaveiro personalizado com nome em dupla face.",
    tags: ["chaveiro", "nome", "personalizado"],
    pricePix: 18.9,
    priceCard: 22.9,
    marketplaceSuggested: 25.13,
    productionWindow: "24h a 48h",
    imageHint: "Chaveiro Nome Dupla Face",
    image: "/assets/images/products/product-37.jpg",
    images: ["/assets/images/products/product-37.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 25,
    dimensions: "6x3x1cm",
    customizable: true,
    readyToShip: false,
  },
  {
    id: "mdh-038",
    sku: "MDH-0038",
    name: "Nome 3D Personalizado",
    category: "Presentes Criativos",
    subcategory: "Nome",
    theme: "Personalizado",
    collection: "Mais vendidos",
    colors: ["Preto", "Branco"],
    grams: 150,
    hours: 5.0,
    complexity: 1.50,
    featured: true,
    description: "Nome personalizado em 3D para decoração.",
    tags: ["nome", "3d", "personalizado"],
    pricePix: 95.9,
    priceCard: 100.9,
    marketplaceSuggested: 105.13,
    productionWindow: "3 a 5 dias",
    imageHint: "Nome 3D Personalizado",
    image: "/assets/images/products/product-38.jpg",
    images: ["/assets/images/products/product-38.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 10,
    dimensions: "30x10x5cm",
    customizable: true,
    readyToShip: false,
  },
  {
    id: "mdh-039",
    sku: "MDH-0039",
    name: "Caixa de Música",
    category: "Presentes Criativos",
    subcategory: "Caixa",
    theme: "Presente",
    collection: "Sob encomenda",
    colors: ["Preto", "Branco"],
    grams: 200,
    hours: 6.0,
    complexity: 1.60,
    featured: false,
    description: "Caixa de música decorativa com mecanismo 3D.",
    tags: ["caixa", "música", "presente"],
    pricePix: 125.9,
    priceCard: 130.9,
    marketplaceSuggested: 135.13,
    productionWindow: "5 a 7 dias",
    imageHint: "Caixa de Música",
    image: "/assets/images/products/product-39.jpg",
    images: ["/assets/images/products/product-39.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 2,
    dimensions: "15x15x10cm",
    customizable: true,
    readyToShip: false,
  },
  {
    id: "mdh-040",
    sku: "MDH-0040",
    name: "Porta-Retrato Personalizado",
    category: "Presentes Criativos",
    subcategory: "Porta-Retrato",
    theme: "Personalizado",
    collection: "Sob encomenda",
    colors: ["Preto", "Branco"],
    grams: 100,
    hours: 3.5,
    complexity: 1.40,
    featured: false,
    description: "Porta-retrato personalizado com design 3D.",
    tags: ["porta-retrato", "personalizado", "presente"],
    pricePix: 65.9,
    priceCard: 70.9,
    marketplaceSuggested: 75.13,
    productionWindow: "3 a 5 dias",
    imageHint: "Porta-Retrato Personalizado",
    image: "/assets/images/products/product-40.jpg",
    images: ["/assets/images/products/product-40.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 8,
    dimensions: "15x10x3cm",
    customizable: true,
    readyToShip: false,
  },
  {
    id: "mdh-041",
    sku: "MDH-0041",
    name: "Aniversário 3D",
    category: "Presentes Criativos",
    subcategory: "Aniversário",
    theme: "Presente",
    collection: "Sob encomenda",
    colors: ["Colorido"],
    grams: 120,
    hours: 4.0,
    complexity: 1.45,
    featured: false,
    description: "Decoração de aniversário personalizada em 3D.",
    tags: ["aniversário", "3d", "presente"],
    pricePix: 78.9,
    priceCard: 83.9,
    marketplaceSuggested: 88.13,
    productionWindow: "3 a 5 dias",
    imageHint: "Aniversário 3D",
    image: "/assets/images/products/product-41.jpg",
    images: ["/assets/images/products/product-41.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 5,
    dimensions: "25x15x5cm",
    customizable: true,
    readyToShip: false,
  },
  {
    id: "mdh-042",
    sku: "MDH-0042",
    name: "Mensagem em 3D",
    category: "Presentes Criativos",
    subcategory: "Mensagem",
    theme: "Personalizado",
    collection: "Sob encomenda",
    colors: ["Preto", "Branco"],
    grams: 80,
    hours: 3.0,
    complexity: 1.35,
    featured: false,
    description: "Mensagem personalizada gravada em 3D.",
    tags: ["mensagem", "3d", "personalizado"],
    pricePix: 52.9,
    priceCard: 57.9,
    marketplaceSuggested: 62.13,
    productionWindow: "3 a 5 dias",
    imageHint: "Mensagem em 3D",
    image: "/assets/images/products/product-42.jpg",
    images: ["/assets/images/products/product-42.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 12,
    dimensions: "20x10x3cm",
    customizable: true,
    readyToShip: false,
  },
  {
    id: "mdh-043",
    sku: "MDH-0043",
    name: "Mini Troféu Personalizado",
    category: "Presentes Criativos",
    subcategory: "Troféu",
    theme: "Presente",
    collection: "Sob encomenda",
    colors: ["Dourado", "Prata"],
    grams: 100,
    hours: 3.5,
    complexity: 1.40,
    featured: false,
    description: "Mini troféu personalizado para conquistas.",
    tags: ["troféu", "personalizado", "presente"],
    pricePix: 65.9,
    priceCard: 70.9,
    marketplaceSuggested: 75.13,
    productionWindow: "3 a 5 dias",
    imageHint: "Mini Troféu Personalizado",
    image: "/assets/images/products/product-43.jpg",
    images: ["/assets/images/products/product-43.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 8,
    dimensions: "10x10x15cm",
    customizable: true,
    readyToShip: false,
  },
  {
    id: "mdh-044",
    sku: "MDH-0044",
    name: "Marcador de Página 3D",
    category: "Presentes Criativos",
    subcategory: "Marcador",
    theme: "Livro",
    collection: "Pronta entrega",
    colors: ["Preto", "Branco"],
    grams: 15,
    hours: 0.8,
    complexity: 1.10,
    featured: false,
    description: "Marcador de página decorativo em 3D.",
    tags: ["marcador", "página", "livro"],
    pricePix: 12.9,
    priceCard: 15.9,
    marketplaceSuggested: 18.13,
    productionWindow: "24h a 48h",
    imageHint: "Marcador de Página 3D",
    image: "/assets/images/products/product-44.jpg",
    images: ["/assets/images/products/product-44.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Pronta entrega",
    stock: 30,
    dimensions: "5x2x0.5cm",
    customizable: true,
    readyToShip: true,
  },
  {
    id: "mdh-045",
    sku: "MDH-0045",
    name: "Abraçadeira Personalizada",
    category: "Presentes Criativos",
    subcategory: "Acessório",
    theme: "Personalizado",
    collection: "Sob encomenda",
    colors: ["Preto", "Branco"],
    grams: 30,
    hours: 1.8,
    complexity: 1.25,
    featured: false,
    description: "Abraçadeira personalizada com nome ou frase.",
    tags: ["abraçadeira", "personalizado", "acessório"],
    pricePix: 22.9,
    priceCard: 26.9,
    marketplaceSuggested: 29.13,
    productionWindow: "24h a 48h",
    imageHint: "Abraçadeira Personalizada",
    image: "/assets/images/products/product-45.jpg",
    images: ["/assets/images/products/product-45.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 20,
    dimensions: "8x5x2cm",
    customizable: true,
    readyToShip: false,
  },
  {
    id: "mdh-046",
    sku: "MDH-0046",
    name: "Pingente Personalizado",
    category: "Presentes Criativos",
    subcategory: "Pingente",
    theme: "Personalizado",
    collection: "Sob encomenda",
    colors: ["Prata", "Dourado"],
    grams: 20,
    hours: 1.2,
    complexity: 1.15,
    featured: false,
    description: "Pingente personalizado para colar ou chaveiro.",
    tags: ["pingente", "personalizado", "jóia"],
    pricePix: 15.9,
    priceCard: 18.9,
    marketplaceSuggested: 21.13,
    productionWindow: "24h a 48h",
    imageHint: "Pingente Personalizado",
    image: "/assets/images/products/product-46.jpg",
    images: ["/assets/images/products/product-46.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 25,
    dimensions: "4x3x1cm",
    customizable: true,
    readyToShip: false,
  },
  {
    id: "mdh-047",
    sku: "MDH-0047",
    name: "Calendário 3D",
    category: "Presentes Criativos",
    subcategory: "Calendário",
    theme: "Casa",
    collection: "Sob encomenda",
    colors: ["Preto", "Branco"],
    grams: 180,
    hours: 5.5,
    complexity: 1.55,
    featured: false,
    description: "Calendário decorativo em 3D para mesa.",
    tags: ["calendário", "3d", "decoração"],
    pricePix: 115.9,
    priceCard: 120.9,
    marketplaceSuggested: 125.13,
    productionWindow: "5 a 7 dias",
    imageHint: "Calendário 3D",
    image: "/assets/images/products/product-47.jpg",
    images: ["/assets/images/products/product-47.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 3,
    dimensions: "20x15x5cm",
    customizable: true,
    readyToShip: false,
  },
  {
    id: "mdh-048",
    sku: "MDH-0048",
    name: "Copo Personalizado",
    category: "Presentes Criativos",
    subcategory: "Copo",
    theme: "Personalizado",
    collection: "Sob encomenda",
    colors: ["Preto", "Branco"],
    grams: 80,
    hours: 3.0,
    complexity: 1.35,
    featured: false,
    description: "Copo personalizado com design 3D.",
    tags: ["copo", "personalizado", "bebida"],
    pricePix: 52.9,
    priceCard: 57.9,
    marketplaceSuggested: 62.13,
    productionWindow: "3 a 5 dias",
    imageHint: "Copo Personalizado",
    image: "/assets/images/products/product-48.jpg",
    images: ["/assets/images/products/product-48.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 15,
    dimensions: "8x8x10cm",
    customizable: true,
    readyToShip: false,
  },
  // Utilidades Reais (12 produtos)
  {
    id: "mdh-049",
    sku: "MDH-0049",
    name: "Suporte para Monitor",
    category: "Utilidades Reais",
    subcategory: "Suporte",
    theme: "Setup",
    collection: "Sob encomenda",
    colors: ["Preto", "Branco"],
    grams: 200,
    hours: 6.0,
    complexity: 1.60,
    featured: false,
    description: "Suporte ajustável para monitor de computador.",
    tags: ["suporte", "monitor", "setup"],
    pricePix: 125.9,
    priceCard: 130.9,
    marketplaceSuggested: 135.13,
    productionWindow: "5 a 7 dias",
    imageHint: "Suporte para Monitor",
    image: "/assets/images/products/product-49.jpg",
    images: ["/assets/images/products/product-49.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 4,
    dimensions: "25x20x15cm",
    customizable: false,
    readyToShip: false,
  },
  {
    id: "mdh-050",
    sku: "MDH-0050",
    name: "Organizador de Cabo USB",
    category: "Utilidades Reais",
    subcategory: "Organizador",
    theme: "Setup",
    collection: "Pronta entrega",
    colors: ["Preto", "Branco"],
    grams: 35,
    hours: 2.0,
    complexity: 1.22,
    featured: false,
    description: "Organizador para cabos USB e carregadores.",
    tags: ["organizador", "usb", "cabo"],
    pricePix: 25.9,
    priceCard: 29.9,
    marketplaceSuggested: 32.13,
    productionWindow: "24h a 48h",
    imageHint: "Organizador de Cabo USB",
    image: "/assets/images/products/product-50.jpg",
    images: ["/assets/images/products/product-50.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Pronta entrega",
    stock: 18,
    dimensions: "10x8x3cm",
    customizable: false,
    readyToShip: true,
  },
  {
    id: "mdh-051",
    sku: "MDH-0051",
    name: "Gancho para Chaves",
    category: "Utilidades Reais",
    subcategory: "Gancho",
    theme: "Casa",
    collection: "Pronta entrega",
    colors: ["Preto", "Branco"],
    grams: 40,
    hours: 2.2,
    complexity: 1.25,
    featured: false,
    description: "Gancho organizador para chaves e acessórios.",
    tags: ["gancho", "chaves", "organização"],
    pricePix: 28.9,
    priceCard: 32.9,
    marketplaceSuggested: 35.13,
    productionWindow: "24h a 48h",
    imageHint: "Gancho para Chaves",
    image: "/assets/images/products/product-51.jpg",
    images: ["/assets/images/products/product-51.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Pronta entrega",
    stock: 22,
    dimensions: "12x6x4cm",
    customizable: true,
    readyToShip: true,
  },
  {
    id: "mdh-052",
    sku: "MDH-0052",
    name: "Suporte para Livros",
    category: "Utilidades Reais",
    subcategory: "Suporte",
    theme: "Casa",
    collection: "Sob encomenda",
    colors: ["Preto", "Branco"],
    grams: 150,
    hours: 5.0,
    complexity: 1.50,
    featured: false,
    description: "Suporte para livros em formato de estante.",
    tags: ["suporte", "livros", "estante"],
    pricePix: 95.9,
    priceCard: 100.9,
    marketplaceSuggested: 105.13,
    productionWindow: "3 a 5 dias",
    imageHint: "Suporte para Livros",
    image: "/assets/images/products/product-52.jpg",
    images: ["/assets/images/products/product-52.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 6,
    dimensions: "25x15x20cm",
    customizable: true,
    readyToShip: false,
  },
  {
    id: "mdh-053",
    sku: "MDH-0053",
    name: "Caixa Organizadora",
    category: "Utilidades Reais",
    subcategory: "Caixa",
    theme: "Casa",
    collection: "Pronta entrega",
    colors: ["Preto", "Branco"],
    grams: 120,
    hours: 4.0,
    complexity: 1.45,
    featured: false,
    description: "Caixa organizadora para pequenos objetos.",
    tags: ["caixa", "organizadora", "armazenamento"],
    pricePix: 75.9,
    priceCard: 80.9,
    marketplaceSuggested: 85.13,
    productionWindow: "3 a 5 dias",
    imageHint: "Caixa Organizadora",
    image: "/assets/images/products/product-53.jpg",
    images: ["/assets/images/products/product-53.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Pronta entrega",
    stock: 12,
    dimensions: "20x15x10cm",
    customizable: true,
    readyToShip: true,
  },
  {
    id: "mdh-054",
    sku: "MDH-0054",
    name: "Suporte para Plantas",
    category: "Utilidades Reais",
    subcategory: "Suporte",
    theme: "Casa",
    collection: "Sob encomenda",
    colors: ["Preto", "Branco"],
    grams: 100,
    hours: 3.5,
    complexity: 1.40,
    featured: false,
    description: "Suporte para vasos de plantas suspensos.",
    tags: ["suporte", "plantas", "jardim"],
    pricePix: 65.9,
    priceCard: 70.9,
    marketplaceSuggested: 75.13,
    productionWindow: "3 a 5 dias",
    imageHint: "Suporte para Plantas",
    image: "/assets/images/products/product-54.jpg",
    images: ["/assets/images/products/product-54.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 8,
    dimensions: "20x10x5cm",
    customizable: false,
    readyToShip: false,
  },
  {
    id: "mdh-055",
    sku: "MDH-0055",
    name: "Prateleira Flutuante",
    category: "Utilidades Reais",
    subcategory: "Prateleira",
    theme: "Casa",
    collection: "Sob encomenda",
    colors: ["Preto", "Branco"],
    grams: 180,
    hours: 5.5,
    complexity: 1.55,
    featured: false,
    description: "Prateleira flutuante para decoração e organização.",
    tags: ["prateleira", "flutuante", "decoração"],
    pricePix: 115.9,
    priceCard: 120.9,
    marketplaceSuggested: 125.13,
    productionWindow: "5 a 7 dias",
    imageHint: "Prateleira Flutuante",
    image: "/assets/images/products/product-55.jpg",
    images: ["/assets/images/products/product-55.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 5,
    dimensions: "40x10x5cm",
    customizable: true,
    readyToShip: false,
  },
  {
    id: "mdh-056",
    sku: "MDH-0056",
    name: "Suporte para Bicicleta",
    category: "Utilidades Reais",
    subcategory: "Suporte",
    theme: "Esporte",
    collection: "Sob encomenda",
    colors: ["Preto", "Branco"],
    grams: 250,
    hours: 7.0,
    complexity: 1.70,
    featured: false,
    description: "Suporte para bicicleta na parede ou chão.",
    tags: ["suporte", "bicicleta", "esporte"],
    pricePix: 155.9,
    priceCard: 160.9,
    marketplaceSuggested: 165.13,
    productionWindow: "7 a 10 dias",
    imageHint: "Suporte para Bicicleta",
    image: "/assets/images/products/product-56.jpg",
    images: ["/assets/images/products/product-56.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 2,
    dimensions: "30x20x15cm",
    customizable: false,
    readyToShip: false,
  },
  {
    id: "mdh-057",
    sku: "MDH-0057",
    name: "Organizador de Maquiagem",
    category: "Utilidades Reais",
    subcategory: "Organizador",
    theme: "Beleza",
    collection: "Sob encomenda",
    colors: ["Rosa", "Branco"],
    grams: 80,
    hours: 3.0,
    complexity: 1.35,
    featured: false,
    description: "Organizador para produtos de maquiagem.",
    tags: ["organizador", "maquiagem", "beleza"],
    pricePix: 52.9,
    priceCard: 57.9,
    marketplaceSuggested: 62.13,
    productionWindow: "3 a 5 dias",
    imageHint: "Organizador de Maquiagem",
    image: "/assets/images/products/product-57.jpg",
    images: ["/assets/images/products/product-57.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 10,
    dimensions: "15x10x8cm",
    customizable: true,
    readyToShip: false,
  },
  {
    id: "mdh-058",
    sku: "MDH-0058",
    name: "Suporte para Tablet",
    category: "Utilidades Reais",
    subcategory: "Suporte",
    theme: "Setup",
    collection: "Pronta entrega",
    colors: ["Preto", "Branco"],
    grams: 60,
    hours: 2.8,
    complexity: 1.30,
    featured: false,
    description: "Suporte ajustável para tablet ou e-reader.",
    tags: ["suporte", "tablet", "leitura"],
    pricePix: 42.9,
    priceCard: 47.9,
    marketplaceSuggested: 52.13,
    productionWindow: "24h a 48h",
    imageHint: "Suporte para Tablet",
    image: "/assets/images/products/product-58.jpg",
    images: ["/assets/images/products/product-58.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Pronta entrega",
    stock: 14,
    dimensions: "15x10x8cm",
    customizable: false,
    readyToShip: true,
  },
  {
    id: "mdh-059",
    sku: "MDH-0059",
    name: "Caixa para Joias",
    category: "Utilidades Reais",
    subcategory: "Caixa",
    theme: "Casa",
    collection: "Sob encomenda",
    colors: ["Preto", "Branco"],
    grams: 120,
    hours: 4.0,
    complexity: 1.45,
    featured: false,
    description: "Caixa organizadora para joias e acessórios.",
    tags: ["caixa", "joias", "organização"],
    pricePix: 78.9,
    priceCard: 83.9,
    marketplaceSuggested: 88.13,
    productionWindow: "3 a 5 dias",
    imageHint: "Caixa para Joias",
    image: "/assets/images/products/product-59.jpg",
    images: ["/assets/images/products/product-59.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 7,
    dimensions: "15x10x8cm",
    customizable: true,
    readyToShip: false,
  },
  {
    id: "mdh-060",
    sku: "MDH-0060",
    name: "Suporte para Garrafa",
    category: "Utilidades Reais",
    subcategory: "Suporte",
    theme: "Casa",
    collection: "Pronta entrega",
    colors: ["Preto", "Branco"],
    grams: 70,
    hours: 3.0,
    complexity: 1.35,
    featured: false,
    description: "Suporte para garrafas de vinho ou água.",
    tags: ["suporte", "garrafa", "cozinha"],
    pricePix: 48.9,
    priceCard: 53.9,
    marketplaceSuggested: 58.13,
    productionWindow: "3 a 5 dias",
    imageHint: "Suporte para Garrafa",
    image: "/assets/images/products/product-60.jpg",
    images: ["/assets/images/products/product-60.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Pronta entrega",
    stock: 16,
    dimensions: "12x8x15cm",
    customizable: false,
    readyToShip: true,
  },
];

export const catalog = curatedCatalog;
export const featuredCatalog = curatedCatalog.filter((item) => item.featured).slice(0, 12);
export const categories = Array.from(new Set(curatedCatalog.map((item) => item.category)));
export const collections = Array.from(new Set(curatedCatalog.map((item) => item.collection)));

export function getProductUrl(product: Product) {
  return `/catalogo/${product.id}-${slugify(product.name)}`;
}

export function findProduct(id: string) {
  return curatedCatalog.find((item) => item.id === id);
}

export function findProductBySlug(slug: string) {
  return curatedCatalog.find((item) => getProductUrl(item).endsWith(slug));
}

export function searchCatalog(query: string) {
  const normalized = query.trim().toLowerCase();
  if (!normalized) return curatedCatalog;
  return curatedCatalog.filter((item) =>
    [item.name, item.category, item.subcategory, item.theme, item.description, item.collection, item.material, item.finish, ...item.tags]
      .join(" ")
      .toLowerCase()
      .includes(normalized)
  );
}

export const defaultPricingExamples = [
  { title: "Chibi premium", grams: 32, hours: 1.9, complexity: 1.1 },
  { title: "Suporte de controle", grams: 92, hours: 3.2, complexity: 1.35 },
  { title: "Vaso geométrico", grams: 96, hours: 3.8, complexity: 1.4 },
  { title: "Nome 3D personalizado", grams: 86, hours: 3.2, complexity: 1.3 },
].map((item) => ({
  ...item,
  pricePix: calculateSalePrice(item.grams, item.hours, item.complexity, "pix", "site"),
  priceCard: calculateSalePrice(item.grams, item.hours, item.complexity, "cartao", "site"),
}));

export const deliverySummary = [...deliveryZones];
