import { deliveryZones } from "@/lib/constants";
import { slugify } from "@/lib/utils";

export type PaymentMethod = "pix" | "cartao" | "boleto";
export type SalesChannel = "site" | "mercadolivre" | "shopee" | "whatsapp";
export type Product = {
  id: string;
  sku: string;
  name: string;
  category: string;
  subcategory: string;
  theme: string;
  collection: string;
  colors: string[];
  grams: number;
  hours: number;
  complexity: number;
  featured: boolean;
  description: string;
  tags: string[];
  pricePix: number;
  priceCard: number;
  marketplaceSuggested: number;
  productionWindow: string;
  imageHint: string;
  image?: string;
  images?: string[];
  material: string;
  finish: string;
  status: "Pronta entrega" | "Sob encomenda";
  stock: number;
  dimensions: string;
  customizable: boolean;
  readyToShip?: boolean;
};

const filamentCostPerGram = 0.11;

function toPriceEnding(value: number) {
  const base = Math.max(9, Math.ceil(value));
  return Number((base - 0.1).toFixed(2));
}

export function calculateBaseCost(grams: number, hours: number, complexity = 1) {
  const material = grams * filamentCostPerGram;
  const machine = Math.max(2, hours * 2.75);
  const acabamento = Math.max(1.5, complexity * 2.2);
  return Number((material + machine + acabamento).toFixed(2));
}

export function calculateSalePrice(
  grams: number,
  hours: number,
  complexity = 1,
  paymentMethod: PaymentMethod = "pix",
  channel: SalesChannel = "site"
) {
  let price = calculateBaseCost(grams, hours, complexity) * 1.95;
  if (paymentMethod === "cartao") price *= 1.12;
  if (paymentMethod === "boleto") price *= 1.08;
  if (channel === "mercadolivre") price *= 1.15;
  if (channel === "shopee") price *= 1.12;
  return toPriceEnding(price);
}

const curatedCatalog: Product[] = [
  {
    id: "mdh-001",
    sku: "MDH-0001",
    name: "Hello Kitty Chibi Premium",
    category: "Anime & Geek",
    subcategory: "Chibi",
    theme: "Chibi",
    collection: "Mais vendidos",
    colors: ["Rosa", "Branco"],
    grams: 32,
    hours: 1.9,
    complexity: 1.27,
    featured: true,
    description: "Peça compacta e marcante para colecionar, decorar setup ou presentear. Produzida em PLA Silk com acabamento premium e conferência visual antes do envio. Feita no Rio de Janeiro com janela de produção rápida e satisfação garantida.",
    tags: ["kawaii", "presente", "pronta entrega"],
    pricePix: 29.9,
    priceCard: 34.9,
    marketplaceSuggested: 39.09,
    productionWindow: "24h a 48h",
    imageHint: "Hello Kitty Chibi Premium",
    image: "/catalog-assets/product-01.jpg",
    images: ["/catalog-assets/product-01.jpg", "/catalog-assets/product-01-2.jpg", "/catalog-assets/product-01-3.jpg"],
    material: "PLA Silk",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 14,
    dimensions: "8x6x10cm",
    customizable: true,
  },
  {
    id: "mdh-002",
    sku: "MDH-0002",
    name: "Mascote Kawaii Desk Buddy",
    category: "Anime & Geek",
    subcategory: "Mascote",
    theme: "Mascote",
    collection: "Pronta entrega",
    colors: ["Amarelo", "Branco", "Azul"],
    grams: 28,
    hours: 1.7,
    complexity: 1.24,
    featured: false,
    description: "Peça compacta e marcante para colecionar, decorar setup ou presentear. Produzida em PLA Premium com acabamento premium e conferência visual antes do envio. Feita no Rio de Janeiro com janela de produção rápida e satisfação garantida.",
    tags: ["chibi", "mesa", "colecionável"],
    pricePix: 26.9,
    priceCard: 31.9,
    marketplaceSuggested: 35.73,
    productionWindow: "24h a 48h",
    imageHint: "Mascote Kawaii Desk Buddy",
    image: "/catalog-assets/product-02.jpg",
    images: ["/catalog-assets/product-02.jpg", "/catalog-assets/product-02-2.jpg", "/catalog-assets/product-02-3.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Pronta entrega",
    stock: 18,
    dimensions: "7x6x9cm",
    customizable: true,
  },
  {
    id: "mdh-003",
    sku: "MDH-0003",
    name: "Monstro Elétrico Pocket Mini",
    category: "Anime & Geek",
    subcategory: "Colecionável",
    theme: "Colecionável",
    collection: "Mais vendidos",
    colors: ["Amarelo", "Preto"],
    grams: 34,
    hours: 2.1,
    complexity: 1.29,
    featured: true,
    description: "Peça compacta e marcante para colecionar, decorar setup ou presentear. Produzida em PLA Premium com acabamento premium e conferência visual antes do envio. Feita no Rio de Janeiro com janela de produção rápida e satisfação garantida.",
    tags: ["pocket", "geek", "presente"],
    pricePix: 34.9,
    priceCard: 39.9,
    marketplaceSuggested: 44.69,
    productionWindow: "24h a 48h",
    imageHint: "Monstro Elétrico Pocket Mini",
    image: "/catalog-assets/product-03.jpg",
    images: ["/catalog-assets/product-03.jpg", "/catalog-assets/product-03-2.jpg", "/catalog-assets/product-03-3.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 10,
    dimensions: "8x6x11cm",
    customizable: false,
  },
  {
    id: "mdh-004",
    sku: "MDH-0004",
    name: "Espiã Mirim Chibi",
    category: "Anime & Geek",
    subcategory: "Chibi",
    theme: "Chibi",
    collection: "Pronta entrega",
    colors: ["Rosa", "Preto", "Dourado"],
    grams: 38,
    hours: 2.4,
    complexity: 1.33,
    featured: true,
    description: "Peça compacta e marcante para colecionar, decorar setup ou presentear. Produzida em PLA Silk com acabamento premium e conferência visual antes do envio. Feita no Rio de Janeiro com janela de produção rápida e satisfação garantida.",
    tags: ["anime", "fofo", "coleção"],
    pricePix: 33.9,
    priceCard: 38.9,
    marketplaceSuggested: 43.57,
    productionWindow: "24h a 48h",
    imageHint: "Espiã Mirim Chibi",
    image: "/catalog-assets/product-04.jpg",
    images: ["/catalog-assets/product-04.jpg", "/catalog-assets/product-04-2.jpg", "/catalog-assets/product-04-3.jpg"],
    material: "PLA Silk",
    finish: "Premium",
    status: "Pronta entrega",
    stock: 9,
    dimensions: "8x7x11cm",
    customizable: false,
  },
  {
    id: "mdh-005",
    sku: "MDH-0005",
    name: "Mascote Serra Articulado",
    category: "Anime & Geek",
    subcategory: "Articulado",
    theme: "Articulado",
    collection: "Sob encomenda",
    colors: ["Laranja", "Branco"],
    grams: 41,
    hours: 2.8,
    complexity: 1.38,
    featured: false,
    description: "Peça compacta e marcante para colecionar, decorar setup ou presentear. Produzida em PLA Premium com acabamento texturizado e conferência visual antes do envio. Feita no Rio de Janeiro com janela de produção rápida e satisfação garantida.",
    tags: ["articulado", "anime", "display"],
    pricePix: 31.9,
    priceCard: 36.9,
    marketplaceSuggested: 41.33,
    productionWindow: "3 a 5 dias",
    imageHint: "Mascote Serra Articulado",
    image: "/catalog-assets/product-05.jpg",
    images: ["/catalog-assets/product-05.jpg", "/catalog-assets/product-05-2.jpg", "/catalog-assets/product-05-3.jpg"],
    material: "PLA Premium",
    finish: "Texturizado",
    status: "Sob encomenda",
    stock: 7,
    dimensions: "10x7x8cm",
    customizable: false,
  },
  {
    id: "mdh-006",
    sku: "MDH-0006",
    name: "Tripulante Crewmate Neon",
    category: "Anime & Geek",
    subcategory: "Miniatura",
    theme: "Miniatura",
    collection: "Pronta entrega",
    colors: ["Vermelho", "Azul", "Preto"],
    grams: 24,
    hours: 1.2,
    complexity: 1.18,
    featured: false,
    description: "Peça compacta e marcante para colecionar, decorar setup ou presentear. Produzida em PLA Premium com acabamento premium e conferência visual antes do envio. Feita no Rio de Janeiro com janela de produção rápida e satisfação garantida.",
    tags: ["game", "colecionável", "mesa"],
    pricePix: 22.9,
    priceCard: 26.9,
    marketplaceSuggested: 30.13,
    productionWindow: "24h a 48h",
    imageHint: "Tripulante Crewmate Neon",
    image: "/catalog-assets/product-06.jpg",
    images: ["/catalog-assets/product-06.jpg", "/catalog-assets/product-06-2.jpg", "/catalog-assets/product-06-3.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Pronta entrega",
    stock: 20,
    dimensions: "6x5x8cm",
    customizable: true,
  },
  {
    id: "mdh-007",
    sku: "MDH-0007",
    name: "Esfera Monstro de Bolso",
    category: "Anime & Geek",
    subcategory: "Acessório",
    theme: "Acessório",
    collection: "Mais vendidos",
    colors: ["Vermelho", "Branco", "Preto"],
    grams: 22,
    hours: 1.1,
    complexity: 1.17,
    featured: true,
    description: "Peça compacta e marcante para colecionar, decorar setup ou presentear. Produzida em PLA Premium com acabamento premium e conferência visual antes do envio. Feita no Rio de Janeiro com janela de produção rápida e satisfação garantida.",
    tags: ["coleção", "presente", "geek"],
    pricePix: 19.9,
    priceCard: 23.9,
    marketplaceSuggested: 26.77,
    productionWindow: "24h a 48h",
    imageHint: "Esfera Monstro de Bolso",
    image: "/catalog-assets/product-07.jpg",
    images: ["/catalog-assets/product-07.jpg", "/catalog-assets/product-07-2.jpg", "/catalog-assets/product-07-3.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 25,
    dimensions: "7x7x7cm",
    customizable: false,
  },
  {
    id: "mdh-008",
    sku: "MDH-0008",
    name: "Bloco Pixel Aventura",
    category: "Anime & Geek",
    subcategory: "Pixel Art",
    theme: "Pixel Art",
    collection: "Pronta entrega",
    colors: ["Vermelho", "Azul", "Amarelo"],
    grams: 29,
    hours: 1.6,
    complexity: 1.23,
    featured: false,
    description: "Peça compacta e marcante para colecionar, decorar setup ou presentear. Produzida em PLA Premium com acabamento texturizado e conferência visual antes do envio. Feita no Rio de Janeiro com janela de produção rápida e satisfação garantida.",
    tags: ["pixel", "retrô", "decoração"],
    pricePix: 27.9,
    priceCard: 31.9,
    marketplaceSuggested: 35.73,
    productionWindow: "24h a 48h",
    imageHint: "Bloco Pixel Aventura",
    image: "/catalog-assets/product-08.jpg",
    images: ["/catalog-assets/product-08.jpg", "/catalog-assets/product-08-2.jpg", "/catalog-assets/product-08-3.jpg"],
    material: "PLA Premium",
    finish: "Texturizado",
    status: "Pronta entrega",
    stock: 12,
    dimensions: "8x8x8cm",
    customizable: false,
  },
  {
    id: "mdh-009",
    sku: "MDH-0009",
    name: "Cubo Creeper Decor",
    category: "Anime & Geek",
    subcategory: "Pixel Art",
    theme: "Pixel Art",
    collection: "Pronta entrega",
    colors: ["Verde", "Preto"],
    grams: 31,
    hours: 1.8,
    complexity: 1.26,
    featured: false,
    description: "Peça compacta e marcante para colecionar, decorar setup ou presentear. Produzida em PLA Premium com acabamento texturizado e conferência visual antes do envio. Feita no Rio de Janeiro com janela de produção rápida e satisfação garantida.",
    tags: ["minecraft", "quarto", "gift"],
    pricePix: 28.9,
    priceCard: 32.9,
    marketplaceSuggested: 36.85,
    productionWindow: "24h a 48h",
    imageHint: "Cubo Creeper Decor",
    image: "/catalog-assets/product-09.jpg",
    images: ["/catalog-assets/product-09.jpg", "/catalog-assets/product-09-2.jpg", "/catalog-assets/product-09-3.jpg"],
    material: "PLA Premium",
    finish: "Texturizado",
    status: "Pronta entrega",
    stock: 11,
    dimensions: "8x8x9cm",
    customizable: false,
  },
  {
    id: "mdh-010",
    sku: "MDH-0010",
    name: "Dragão Articulado Galáxia",
    category: "Anime & Geek",
    subcategory: "Articulado",
    theme: "Articulado",
    collection: "Lançamentos",
    colors: ["Roxo", "Azul", "Prata"],
    grams: 62,
    hours: 3.6,
    complexity: 1.51,
    featured: true,
    description: "Peça compacta e marcante para colecionar, decorar setup ou presentear. Produzida em PLA Silk com acabamento premium e conferência visual antes do envio. Feita no Rio de Janeiro com janela de produção rápida e satisfação garantida.",
    tags: ["dragão", "articulado", "viral"],
    pricePix: 49.9,
    priceCard: 57.9,
    marketplaceSuggested: 64.85,
    productionWindow: "3 a 5 dias",
    imageHint: "Dragão Articulado Galáxia",
    image: "/catalog-assets/product-10.jpg",
    images: ["/catalog-assets/product-10.jpg", "/catalog-assets/product-10-2.jpg", "/catalog-assets/product-10-3.jpg"],
    material: "PLA Silk",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 6,
    dimensions: "24x6x5cm",
    customizable: true,
  },
  {
    id: "mdh-011",
    sku: "MDH-0011",
    name: "Busto Hero Desk Edition",
    category: "Anime & Geek",
    subcategory: "Busto",
    theme: "Busto",
    collection: "Sob encomenda",
    colors: ["Cinza", "Preto", "Vermelho"],
    grams: 74,
    hours: 4.2,
    complexity: 1.6,
    featured: true,
    description: "Peça compacta e marcante para colecionar, decorar setup ou presentear. Produzida em PLA Premium com acabamento premium e conferência visual antes do envio. Feita no Rio de Janeiro com janela de produção rápida e satisfação garantida.",
    tags: ["busto", "colecionável", "anime"],
    pricePix: 58.9,
    priceCard: 67.9,
    marketplaceSuggested: 76.05,
    productionWindow: "5 a 7 dias",
    imageHint: "Busto Hero Desk Edition",
    image: "/catalog-assets/product-11.jpg",
    images: ["/catalog-assets/product-11.jpg", "/catalog-assets/product-11-2.jpg", "/catalog-assets/product-11-3.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 5,
    dimensions: "9x8x14cm",
    customizable: false,
  },
  {
    id: "mdh-012",
    sku: "MDH-0012",
    name: "Kaiju Mini Display",
    category: "Anime & Geek",
    subcategory: "Busto",
    theme: "Busto",
    collection: "Sob encomenda",
    colors: ["Cinza", "Verde"],
    grams: 79,
    hours: 4.5,
    complexity: 1.65,
    featured: false,
    description: "Peça compacta e marcante para colecionar, decorar setup ou presentear. Produzida em PLA Premium com acabamento premium e conferência visual antes do envio. Feita no Rio de Janeiro com janela de produção rápida e satisfação garantida.",
    tags: ["monster", "display", "coleção"],
    pricePix: 61.9,
    priceCard: 71.9,
    marketplaceSuggested: 80.53,
    productionWindow: "5 a 7 dias",
    imageHint: "Kaiju Mini Display",
    image: "/catalog-assets/product-12.jpg",
    images: ["/catalog-assets/product-12.jpg", "/catalog-assets/product-12-2.jpg", "/catalog-assets/product-12-3.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 4,
    dimensions: "10x8x15cm",
    customizable: false,
  },
  {
    id: "mdh-013",
    sku: "MDH-0013",
    name: "Suporte Headphone Orbit",
    category: "Setup & Organização",
    subcategory: "Suporte",
    theme: "Suporte",
    collection: "Mais vendidos",
    colors: ["Preto", "Branco"],
    grams: 118,
    hours: 4.2,
    complexity: 1.71,
    featured: true,
    description: "Organização prática para mesa, setup ou home office com foco em uso diário. Produzido em PETG com geometria pensada para estabilidade e acabamento técnico. Feito localmente no RJ para entrega mais rápida e reposição simples.",
    tags: ["headphone", "setup", "mesa"],
    pricePix: 49.9,
    priceCard: 57.9,
    marketplaceSuggested: 64.85,
    productionWindow: "3 a 5 dias",
    imageHint: "Suporte Headphone Orbit",
    image: "/catalog-assets/product-13.jpg",
    images: ["/catalog-assets/product-13.jpg", "/catalog-assets/product-13-2.jpg", "/catalog-assets/product-13-3.jpg"],
    material: "PETG",
    finish: "Técnico",
    status: "Sob encomenda",
    stock: 9,
    dimensions: "11x12x24cm",
    customizable: false,
  },
  {
    id: "mdh-014",
    sku: "MDH-0014",
    name: "Organizador de Cabos Snap 6",
    category: "Setup & Organização",
    subcategory: "Organizador",
    theme: "Organizador",
    collection: "Pronta entrega",
    colors: ["Preto", "Branco", "Cinza"],
    grams: 18,
    hours: 0.9,
    complexity: 1.14,
    featured: true,
    description: "Organização prática para mesa, setup ou home office com foco em uso diário. Produzido em PLA Premium com geometria pensada para estabilidade e acabamento premium. Feito localmente no RJ para entrega mais rápida e reposição simples.",
    tags: ["cabos", "mesa", "home office"],
    pricePix: 16.9,
    priceCard: 19.9,
    marketplaceSuggested: 22.29,
    productionWindow: "24h a 48h",
    imageHint: "Organizador de Cabos Snap 6",
    image: "/catalog-assets/product-14.jpg",
    images: ["/catalog-assets/product-14.jpg", "/catalog-assets/product-14-2.jpg", "/catalog-assets/product-14-3.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Pronta entrega",
    stock: 32,
    dimensions: "8x3x2cm",
    customizable: true,
  },
  {
    id: "mdh-015",
    sku: "MDH-0015",
    name: "Dock Celular Vertical Flex",
    category: "Setup & Organização",
    subcategory: "Suporte",
    theme: "Suporte",
    collection: "Pronta entrega",
    colors: ["Preto", "Azul", "Branco"],
    grams: 36,
    hours: 1.4,
    complexity: 1.23,
    featured: true,
    description: "Organização prática para mesa, setup ou home office com foco em uso diário. Produzido em PLA Premium com geometria pensada para estabilidade e acabamento premium. Feito localmente no RJ para entrega mais rápida e reposição simples.",
    tags: ["celular", "mesa", "utilidade"],
    pricePix: 24.9,
    priceCard: 28.9,
    marketplaceSuggested: 32.37,
    productionWindow: "24h a 48h",
    imageHint: "Dock Celular Vertical Flex",
    image: "/catalog-assets/product-15.jpg",
    images: ["/catalog-assets/product-15.jpg", "/catalog-assets/product-15-2.jpg", "/catalog-assets/product-15-3.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Pronta entrega",
    stock: 16,
    dimensions: "8x8x12cm",
    customizable: true,
  },
  {
    id: "mdh-016",
    sku: "MDH-0016",
    name: "Base Controle Dual Charge Stand",
    category: "Setup & Organização",
    subcategory: "Suporte",
    theme: "Suporte",
    collection: "Mais vendidos",
    colors: ["Preto", "Branco"],
    grams: 92,
    hours: 3.2,
    complexity: 1.55,
    featured: true,
    description: "Organização prática para mesa, setup ou home office com foco em uso diário. Produzido em PLA Premium com geometria pensada para estabilidade e acabamento premium. Feito localmente no RJ para entrega mais rápida e reposição simples.",
    tags: ["ps5", "xbox", "setup"],
    pricePix: 42.9,
    priceCard: 49.9,
    marketplaceSuggested: 55.89,
    productionWindow: "3 a 5 dias",
    imageHint: "Base Controle Dual Charge Stand",
    image: "/catalog-assets/product-16.jpg",
    images: ["/catalog-assets/product-16.jpg", "/catalog-assets/product-16-2.jpg", "/catalog-assets/product-16-3.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 12,
    dimensions: "18x9x10cm",
    customizable: false,
  },
  {
    id: "mdh-017",
    sku: "MDH-0017",
    name: "Dock Notebook Airflow",
    category: "Setup & Organização",
    subcategory: "Suporte",
    theme: "Suporte",
    collection: "Sob encomenda",
    colors: ["Preto", "Cinza"],
    grams: 105,
    hours: 4.6,
    complexity: 1.72,
    featured: false,
    description: "Organização prática para mesa, setup ou home office com foco em uso diário. Produzido em PETG com geometria pensada para estabilidade e acabamento técnico. Feito localmente no RJ para entrega mais rápida e reposição simples.",
    tags: ["notebook", "ergonomia", "mesa"],
    pricePix: 54.9,
    priceCard: 63.9,
    marketplaceSuggested: 71.57,
    productionWindow: "3 a 5 dias",
    imageHint: "Dock Notebook Airflow",
    image: "/catalog-assets/product-17.jpg",
    images: ["/catalog-assets/product-17.jpg", "/catalog-assets/product-17-2.jpg", "/catalog-assets/product-17-3.jpg"],
    material: "PETG",
    finish: "Técnico",
    status: "Sob encomenda",
    stock: 7,
    dimensions: "24x7x6cm",
    customizable: false,
  },
  {
    id: "mdh-018",
    sku: "MDH-0018",
    name: "Suporte Webcam Horizon",
    category: "Setup & Organização",
    subcategory: "Acessório",
    theme: "Acessório",
    collection: "Pronta entrega",
    colors: ["Preto", "Branco"],
    grams: 22,
    hours: 1.1,
    complexity: 1.17,
    featured: false,
    description: "Organização prática para mesa, setup ou home office com foco em uso diário. Produzido em PLA Premium com geometria pensada para estabilidade e acabamento premium. Feito localmente no RJ para entrega mais rápida e reposição simples.",
    tags: ["webcam", "monitor", "stream"],
    pricePix: 19.9,
    priceCard: 23.9,
    marketplaceSuggested: 26.77,
    productionWindow: "24h a 48h",
    imageHint: "Suporte Webcam Horizon",
    image: "/catalog-assets/product-18.jpg",
    images: ["/catalog-assets/product-18.jpg", "/catalog-assets/product-18-2.jpg", "/catalog-assets/product-18-3.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Pronta entrega",
    stock: 18,
    dimensions: "6x4x5cm",
    customizable: false,
  },
  {
    id: "mdh-019",
    sku: "MDH-0019",
    name: "Passa-Cabos Magnetic Desk",
    category: "Setup & Organização",
    subcategory: "Organizador",
    theme: "Organizador",
    collection: "Pronta entrega",
    colors: ["Preto", "Cinza", "Azul"],
    grams: 27,
    hours: 1.0,
    complexity: 1.17,
    featured: false,
    description: "Organização prática para mesa, setup ou home office com foco em uso diário. Produzido em PLA Premium com geometria pensada para estabilidade e acabamento premium. Feito localmente no RJ para entrega mais rápida e reposição simples.",
    tags: ["cabo", "desk", "organização"],
    pricePix: 18.9,
    priceCard: 22.9,
    marketplaceSuggested: 25.65,
    productionWindow: "24h a 48h",
    imageHint: "Passa-Cabos Magnetic Desk",
    image: "/catalog-assets/product-19.jpg",
    images: ["/catalog-assets/product-19.jpg", "/catalog-assets/product-19-2.jpg", "/catalog-assets/product-19-3.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Pronta entrega",
    stock: 20,
    dimensions: "9x4x2cm",
    customizable: true,
  },
  {
    id: "mdh-020",
    sku: "MDH-0020",
    name: "Suporte Celular Carrossel",
    category: "Setup & Organização",
    subcategory: "Suporte",
    theme: "Suporte",
    collection: "Mais vendidos",
    colors: ["Branco", "Preto", "Verde"],
    grams: 44,
    hours: 1.9,
    complexity: 1.3,
    featured: false,
    description: "Organização prática para mesa, setup ou home office com foco em uso diário. Produzido em PLA Premium com geometria pensada para estabilidade e acabamento premium. Feito localmente no RJ para entrega mais rápida e reposição simples.",
    tags: ["celular", "vídeo", "mesa"],
    pricePix: 27.9,
    priceCard: 31.9,
    marketplaceSuggested: 35.73,
    productionWindow: "24h a 48h",
    imageHint: "Suporte Celular Carrossel",
    image: "/catalog-assets/product-20.jpg",
    images: ["/catalog-assets/product-20.jpg", "/catalog-assets/product-20-2.jpg", "/catalog-assets/product-20-3.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 15,
    dimensions: "8x8x14cm",
    customizable: true,
  },
  {
    id: "mdh-021",
    sku: "MDH-0021",
    name: "Organizador SD & Cartões",
    category: "Setup & Organização",
    subcategory: "Organizador",
    theme: "Organizador",
    collection: "Pronta entrega",
    colors: ["Preto", "Vermelho"],
    grams: 21,
    hours: 0.8,
    complexity: 1.13,
    featured: false,
    description: "Organização prática para mesa, setup ou home office com foco em uso diário. Produzido em PLA Premium com geometria pensada para estabilidade e acabamento premium. Feito localmente no RJ para entrega mais rápida e reposição simples.",
    tags: ["cartão", "camera", "setup"],
    pricePix: 17.9,
    priceCard: 20.9,
    marketplaceSuggested: 23.41,
    productionWindow: "24h a 48h",
    imageHint: "Organizador SD & Cartões",
    image: "/catalog-assets/product-21.jpg",
    images: ["/catalog-assets/product-21.jpg", "/catalog-assets/product-21-2.jpg", "/catalog-assets/product-21-3.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Pronta entrega",
    stock: 22,
    dimensions: "9x4x2cm",
    customizable: true,
  },
  {
    id: "mdh-022",
    sku: "MDH-0022",
    name: "Suporte Headset Wall Hook",
    category: "Setup & Organização",
    subcategory: "Acessório",
    theme: "Acessório",
    collection: "Pronta entrega",
    colors: ["Preto", "Branco"],
    grams: 35,
    hours: 1.3,
    complexity: 1.22,
    featured: false,
    description: "Organização prática para mesa, setup ou home office com foco em uso diário. Produzido em PETG com geometria pensada para estabilidade e acabamento técnico. Feito localmente no RJ para entrega mais rápida e reposição simples.",
    tags: ["headset", "parede", "setup"],
    pricePix: 23.9,
    priceCard: 27.9,
    marketplaceSuggested: 31.25,
    productionWindow: "24h a 48h",
    imageHint: "Suporte Headset Wall Hook",
    image: "/catalog-assets/product-22.jpg",
    images: ["/catalog-assets/product-22.jpg", "/catalog-assets/product-22-2.jpg", "/catalog-assets/product-22-3.jpg"],
    material: "PETG",
    finish: "Técnico",
    status: "Pronta entrega",
    stock: 14,
    dimensions: "6x5x10cm",
    customizable: false,
  },
  {
    id: "mdh-023",
    sku: "MDH-0023",
    name: "Bandeja Desk EDC",
    category: "Setup & Organização",
    subcategory: "Organizador",
    theme: "Organizador",
    collection: "Sob encomenda",
    colors: ["Preto", "Marrom", "Cinza"],
    grams: 88,
    hours: 3.5,
    complexity: 1.57,
    featured: false,
    description: "Organização prática para mesa, setup ou home office com foco em uso diário. Produzido em PLA Premium com geometria pensada para estabilidade e acabamento premium. Feito localmente no RJ para entrega mais rápida e reposição simples.",
    tags: ["chaves", "carteira", "mesa"],
    pricePix: 39.9,
    priceCard: 46.9,
    marketplaceSuggested: 52.53,
    productionWindow: "3 a 5 dias",
    imageHint: "Bandeja Desk EDC",
    image: "/catalog-assets/product-23.jpg",
    images: ["/catalog-assets/product-23.jpg", "/catalog-assets/product-23-2.jpg", "/catalog-assets/product-23-3.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 8,
    dimensions: "18x12x3cm",
    customizable: true,
  },
  {
    id: "mdh-024",
    sku: "MDH-0024",
    name: "Stand Tablet Creator",
    category: "Setup & Organização",
    subcategory: "Suporte",
    theme: "Suporte",
    collection: "Lançamentos",
    colors: ["Preto", "Cinza"],
    grams: 126,
    hours: 4.9,
    complexity: 1.8,
    featured: true,
    description: "Organização prática para mesa, setup ou home office com foco em uso diário. Produzido em PETG com geometria pensada para estabilidade e acabamento técnico. Feito localmente no RJ para entrega mais rápida e reposição simples.",
    tags: ["tablet", "desenho", "ergonomia"],
    pricePix: 59.9,
    priceCard: 69.9,
    marketplaceSuggested: 78.29,
    productionWindow: "3 a 5 dias",
    imageHint: "Stand Tablet Creator",
    image: "/catalog-assets/product-24.jpg",
    images: ["/catalog-assets/product-24.jpg", "/catalog-assets/product-24-2.jpg", "/catalog-assets/product-24-3.jpg"],
    material: "PETG",
    finish: "Técnico",
    status: "Sob encomenda",
    stock: 6,
    dimensions: "16x12x18cm",
    customizable: false,
  },
  {
    id: "mdh-025",
    sku: "MDH-0025",
    name: "Vaso Geométrico Atlas",
    category: "Casa & Decoração",
    subcategory: "Vaso",
    theme: "Vaso",
    collection: "Mais vendidos",
    colors: ["Areia", "Preto", "Branco"],
    grams: 96,
    hours: 3.8,
    complexity: 1.62,
    featured: true,
    description: "Peça pensada para valorizar ambientes, organizar a rotina ou criar um ponto de destaque visual. Fabricada em PLA Silk com acabamento premium e produção local no Rio de Janeiro. Excelente opção para casa, presente ou composição de decoração.",
    tags: ["vaso", "decoração", "sala"],
    pricePix: 39.9,
    priceCard: 45.9,
    marketplaceSuggested: 51.41,
    productionWindow: "3 a 5 dias",
    imageHint: "Vaso Geométrico Atlas",
    image: "/catalog-assets/product-25.jpg",
    images: ["/catalog-assets/product-25.jpg", "/catalog-assets/product-25-2.jpg", "/catalog-assets/product-25-3.jpg"],
    material: "PLA Silk",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 10,
    dimensions: "12x12x16cm",
    customizable: false,
  },
  {
    id: "mdh-026",
    sku: "MDH-0026",
    name: "Cachepot Linha Aurora",
    category: "Casa & Decoração",
    subcategory: "Vaso",
    theme: "Vaso",
    collection: "Pronta entrega",
    colors: ["Branco", "Terracota", "Preto"],
    grams: 82,
    hours: 3.1,
    complexity: 1.52,
    featured: false,
    description: "Peça pensada para valorizar ambientes, organizar a rotina ou criar um ponto de destaque visual. Fabricada em PLA Premium com acabamento premium e produção local no Rio de Janeiro. Excelente opção para casa, presente ou composição de decoração.",
    tags: ["planta", "decoração", "minimalista"],
    pricePix: 34.9,
    priceCard: 39.9,
    marketplaceSuggested: 44.69,
    productionWindow: "24h a 48h",
    imageHint: "Cachepot Linha Aurora",
    image: "/catalog-assets/product-26.jpg",
    images: ["/catalog-assets/product-26.jpg", "/catalog-assets/product-26-2.jpg", "/catalog-assets/product-26-3.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Pronta entrega",
    stock: 12,
    dimensions: "11x11x13cm",
    customizable: false,
  },
  {
    id: "mdh-027",
    sku: "MDH-0027",
    name: "Luminária LED Lua Minimal",
    category: "Casa & Decoração",
    subcategory: "Luminária",
    theme: "Luminária",
    collection: "Sob encomenda",
    colors: ["Branco", "Preto"],
    grams: 128,
    hours: 5.0,
    complexity: 1.82,
    featured: true,
    description: "Peça pensada para valorizar ambientes, organizar a rotina ou criar um ponto de destaque visual. Fabricada em PLA Premium com acabamento premium e produção local no Rio de Janeiro. Excelente opção para casa, presente ou composição de decoração.",
    tags: ["led", "quarto", "presente"],
    pricePix: 74.9,
    priceCard: 86.9,
    marketplaceSuggested: 97.33,
    productionWindow: "5 a 7 dias",
    imageHint: "Luminária LED Lua Minimal",
    image: "/catalog-assets/product-27.jpg",
    images: ["/catalog-assets/product-27.jpg", "/catalog-assets/product-27-2.jpg", "/catalog-assets/product-27-3.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 6,
    dimensions: "14x14x18cm",
    customizable: true,
  },
  {
    id: "mdh-028",
    sku: "MDH-0028",
    name: "Porta-Chaves Hexa Wall",
    category: "Casa & Decoração",
    subcategory: "Organizador",
    theme: "Organizador",
    collection: "Pronta entrega",
    colors: ["Preto", "Cinza", "Madeira"],
    grams: 58,
    hours: 2.2,
    complexity: 1.36,
    featured: false,
    description: "Peça pensada para valorizar ambientes, organizar a rotina ou criar um ponto de destaque visual. Fabricada em PETG com acabamento técnico e produção local no Rio de Janeiro. Excelente opção para casa, presente ou composição de decoração.",
    tags: ["chaves", "entrada", "casa"],
    pricePix: 29.9,
    priceCard: 34.9,
    marketplaceSuggested: 39.09,
    productionWindow: "24h a 48h",
    imageHint: "Porta-Chaves Hexa Wall",
    image: "/catalog-assets/product-28.jpg",
    images: ["/catalog-assets/product-28.jpg", "/catalog-assets/product-28-2.jpg", "/catalog-assets/product-28-3.jpg"],
    material: "PETG",
    finish: "Técnico",
    status: "Pronta entrega",
    stock: 11,
    dimensions: "18x7x4cm",
    customizable: true,
  },
  {
    id: "mdh-029",
    sku: "MDH-0029",
    name: "Porta-Controle Remote Dock",
    category: "Casa & Decoração",
    subcategory: "Organizador",
    theme: "Organizador",
    collection: "Pronta entrega",
    colors: ["Preto", "Branco"],
    grams: 64,
    hours: 2.4,
    complexity: 1.4,
    featured: false,
    description: "Peça pensada para valorizar ambientes, organizar a rotina ou criar um ponto de destaque visual. Fabricada em PLA Premium com acabamento premium e produção local no Rio de Janeiro. Excelente opção para casa, presente ou composição de decoração.",
    tags: ["sala", "controle", "organização"],
    pricePix: 31.9,
    priceCard: 36.9,
    marketplaceSuggested: 41.33,
    productionWindow: "24h a 48h",
    imageHint: "Porta-Controle Remote Dock",
    image: "/catalog-assets/product-29.jpg",
    images: ["/catalog-assets/product-29.jpg", "/catalog-assets/product-29-2.jpg", "/catalog-assets/product-29-3.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Pronta entrega",
    stock: 10,
    dimensions: "17x9x8cm",
    customizable: false,
  },
  {
    id: "mdh-030",
    sku: "MDH-0030",
    name: "Porta-Velas Spiral Glow",
    category: "Casa & Decoração",
    subcategory: "Decorativo",
    theme: "Decorativo",
    collection: "Sob encomenda",
    colors: ["Dourado", "Preto", "Branco"],
    grams: 72,
    hours: 3.0,
    complexity: 1.48,
    featured: false,
    description: "Peça pensada para valorizar ambientes, organizar a rotina ou criar um ponto de destaque visual. Fabricada em PLA Silk com acabamento premium e produção local no Rio de Janeiro. Excelente opção para casa, presente ou composição de decoração.",
    tags: ["vela", "mesa posta", "decor"],
    pricePix: 36.9,
    priceCard: 42.9,
    marketplaceSuggested: 48.05,
    productionWindow: "3 a 5 dias",
    imageHint: "Porta-Velas Spiral Glow",
    image: "/catalog-assets/product-30.jpg",
    images: ["/catalog-assets/product-30.jpg", "/catalog-assets/product-30-2.jpg", "/catalog-assets/product-30-3.jpg"],
    material: "PLA Silk",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 7,
    dimensions: "9x9x12cm",
    customizable: false,
  },
  {
    id: "mdh-031",
    sku: "MDH-0031",
    name: "Placa Pix Balcão Clean",
    category: "Casa & Decoração",
    subcategory: "Comercial",
    theme: "Comercial",
    collection: "Pronta entrega",
    colors: ["Branco", "Preto", "Verde"],
    grams: 38,
    hours: 1.4,
    complexity: 1.23,
    featured: true,
    description: "Peça pensada para valorizar ambientes, organizar a rotina ou criar um ponto de destaque visual. Fabricada em PLA Premium com acabamento premium e produção local no Rio de Janeiro. Excelente opção para casa, presente ou composição de decoração.",
    tags: ["pix", "loja", "negócio"],
    pricePix: 24.9,
    priceCard: 28.9,
    marketplaceSuggested: 32.37,
    productionWindow: "24h a 48h",
    imageHint: "Placa Pix Balcão Clean",
    image: "/catalog-assets/product-31.jpg",
    images: ["/catalog-assets/product-31.jpg", "/catalog-assets/product-31-2.jpg", "/catalog-assets/product-31-3.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Pronta entrega",
    stock: 15,
    dimensions: "12x8x4cm",
    customizable: true,
  },
  {
    id: "mdh-032",
    sku: "MDH-0032",
    name: "Gancho Multiuso Home Fix",
    category: "Casa & Decoração",
    subcategory: "Utilitário",
    theme: "Utilitário",
    collection: "Pronta entrega",
    colors: ["Preto", "Branco"],
    grams: 19,
    hours: 0.7,
    complexity: 1.12,
    featured: false,
    description: "Peça pensada para valorizar ambientes, organizar a rotina ou criar um ponto de destaque visual. Fabricada em PETG com acabamento técnico e produção local no Rio de Janeiro. Excelente opção para casa, presente ou composição de decoração.",
    tags: ["gancho", "banheiro", "cozinha"],
    pricePix: 15.9,
    priceCard: 18.9,
    marketplaceSuggested: 21.17,
    productionWindow: "24h a 48h",
    imageHint: "Gancho Multiuso Home Fix",
    image: "/catalog-assets/product-32.jpg",
    images: ["/catalog-assets/product-32.jpg", "/catalog-assets/product-32-2.jpg", "/catalog-assets/product-32-3.jpg"],
    material: "PETG",
    finish: "Técnico",
    status: "Pronta entrega",
    stock: 24,
    dimensions: "4x4x6cm",
    customizable: false,
  },
  {
    id: "mdh-033",
    sku: "MDH-0033",
    name: "Porta-Esponja Dry Sink",
    category: "Casa & Decoração",
    subcategory: "Utilitário",
    theme: "Utilitário",
    collection: "Pronta entrega",
    colors: ["Cinza", "Preto", "Branco"],
    grams: 41,
    hours: 1.6,
    complexity: 1.26,
    featured: false,
    description: "Peça pensada para valorizar ambientes, organizar a rotina ou criar um ponto de destaque visual. Fabricada em PETG com acabamento técnico e produção local no Rio de Janeiro. Excelente opção para casa, presente ou composição de decoração.",
    tags: ["pia", "cozinha", "casa"],
    pricePix: 21.9,
    priceCard: 25.9,
    marketplaceSuggested: 29.01,
    productionWindow: "24h a 48h",
    imageHint: "Porta-Esponja Dry Sink",
    image: "/catalog-assets/product-33.jpg",
    images: ["/catalog-assets/product-33.jpg", "/catalog-assets/product-33-2.jpg", "/catalog-assets/product-33-3.jpg"],
    material: "PETG",
    finish: "Técnico",
    status: "Pronta entrega",
    stock: 18,
    dimensions: "10x7x5cm",
    customizable: false,
  },
  {
    id: "mdh-034",
    sku: "MDH-0034",
    name: "Mandala Wall Decor 3D",
    category: "Casa & Decoração",
    subcategory: "Parede",
    theme: "Parede",
    collection: "Sob encomenda",
    colors: ["Branco", "Preto", "Dourado"],
    grams: 134,
    hours: 5.4,
    complexity: 1.88,
    featured: false,
    description: "Peça pensada para valorizar ambientes, organizar a rotina ou criar um ponto de destaque visual. Fabricada em PLA Premium com acabamento premium e produção local no Rio de Janeiro. Excelente opção para casa, presente ou composição de decoração.",
    tags: ["parede", "boho", "decoração"],
    pricePix: 64.9,
    priceCard: 74.9,
    marketplaceSuggested: 83.89,
    productionWindow: "5 a 7 dias",
    imageHint: "Mandala Wall Decor 3D",
    image: "/catalog-assets/product-34.jpg",
    images: ["/catalog-assets/product-34.jpg", "/catalog-assets/product-34-2.jpg", "/catalog-assets/product-34-3.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 5,
    dimensions: "22x22x2cm",
    customizable: false,
  },
  {
    id: "mdh-035",
    sku: "MDH-0035",
    name: "Suporte Escova Care",
    category: "Casa & Decoração",
    subcategory: "Banheiro",
    theme: "Banheiro",
    collection: "Pronta entrega",
    colors: ["Branco", "Preto"],
    grams: 33,
    hours: 1.2,
    complexity: 1.2,
    featured: false,
    description: "Peça pensada para valorizar ambientes, organizar a rotina ou criar um ponto de destaque visual. Fabricada em PETG com acabamento técnico e produção local no Rio de Janeiro. Excelente opção para casa, presente ou composição de decoração.",
    tags: ["banheiro", "higiene", "organização"],
    pricePix: 19.9,
    priceCard: 23.9,
    marketplaceSuggested: 26.77,
    productionWindow: "24h a 48h",
    imageHint: "Suporte Escova Care",
    image: "/catalog-assets/product-35.jpg",
    images: ["/catalog-assets/product-35.jpg", "/catalog-assets/product-35-2.jpg", "/catalog-assets/product-35-3.jpg"],
    material: "PETG",
    finish: "Técnico",
    status: "Pronta entrega",
    stock: 17,
    dimensions: "7x7x8cm",
    customizable: false,
  },
  {
    id: "mdh-036",
    sku: "MDH-0036",
    name: "Luminária Pixel Room Icon",
    category: "Casa & Decoração",
    subcategory: "Luminária",
    theme: "Luminária",
    collection: "Lançamentos",
    colors: ["Azul", "Amarelo", "Branco"],
    grams: 116,
    hours: 4.6,
    complexity: 1.75,
    featured: true,
    description: "Peça pensada para valorizar ambientes, organizar a rotina ou criar um ponto de destaque visual. Fabricada em PLA Premium com acabamento premium e produção local no Rio de Janeiro. Excelente opção para casa, presente ou composição de decoração.",
    tags: ["quarto", "game", "led"],
    pricePix: 69.9,
    priceCard: 79.9,
    marketplaceSuggested: 89.49,
    productionWindow: "3 a 5 dias",
    imageHint: "Luminária Pixel Room Icon",
    image: "/catalog-assets/product-36.jpg",
    images: ["/catalog-assets/product-36.jpg", "/catalog-assets/product-36-2.jpg", "/catalog-assets/product-36-3.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 6,
    dimensions: "16x6x18cm",
    customizable: true,
  },
  {
    id: "mdh-037",
    sku: "MDH-0037",
    name: "Chaveiro Nome Dupla Face",
    category: "Presentes Criativos",
    subcategory: "Chaveiro",
    theme: "Chaveiro",
    collection: "Mais vendidos",
    colors: ["Preto", "Branco", "Rosa", "Azul"],
    grams: 12,
    hours: 0.5,
    complexity: 1.08,
    featured: true,
    description: "Pensado para surpreender com personalização rápida e acabamento bonito de verdade. Produzido em PLA Premium com acabamento premium e revisão antes do envio. Uma opção forte para presentes criativos feitos no RJ com atendimento humano.",
    tags: ["nome", "presente", "lembrança"],
    pricePix: 12.9,
    priceCard: 14.9,
    marketplaceSuggested: 16.69,
    productionWindow: "24h a 48h",
    imageHint: "Chaveiro Nome Dupla Face",
    image: "/catalog-assets/product-37.jpg",
    images: ["/catalog-assets/product-37.jpg", "/catalog-assets/product-37-2.jpg", "/catalog-assets/product-37-3.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 40,
    dimensions: "5x3x0.4cm",
    customizable: true,
  },
  {
    id: "mdh-038",
    sku: "MDH-0038",
    name: "Nome 3D Desk Decor",
    category: "Presentes Criativos",
    subcategory: "Nome 3D",
    theme: "Nome 3D",
    collection: "Mais vendidos",
    colors: ["Branco", "Dourado", "Azul"],
    grams: 86,
    hours: 3.2,
    complexity: 1.54,
    featured: true,
    description: "Pensado para surpreender com personalização rápida e acabamento bonito de verdade. Produzido em PLA Silk com acabamento premium e revisão antes do envio. Uma opção forte para presentes criativos feitos no RJ com atendimento humano.",
    tags: ["nome 3d", "mesa", "presente"],
    pricePix: 49.9,
    priceCard: 57.9,
    marketplaceSuggested: 64.85,
    productionWindow: "3 a 5 dias",
    imageHint: "Nome 3D Desk Decor",
    image: "/catalog-assets/product-38.jpg",
    images: ["/catalog-assets/product-38.jpg", "/catalog-assets/product-38-2.jpg", "/catalog-assets/product-38-3.jpg"],
    material: "PLA Silk",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 11,
    dimensions: "20x3x8cm",
    customizable: true,
  },
  {
    id: "mdh-039",
    sku: "MDH-0039",
    name: "Topo de Bolo Personalizado",
    category: "Presentes Criativos",
    subcategory: "Festas",
    theme: "Festas",
    collection: "Sob encomenda",
    colors: ["Preto", "Dourado", "Rosa"],
    grams: 24,
    hours: 1.0,
    complexity: 1.16,
    featured: false,
    description: "Pensado para surpreender com personalização rápida e acabamento bonito de verdade. Produzido em PLA Premium com acabamento premium e revisão antes do envio. Uma opção forte para presentes criativos feitos no RJ com atendimento humano.",
    tags: ["bolo", "festa", "personalizado"],
    pricePix: 22.9,
    priceCard: 26.9,
    marketplaceSuggested: 30.13,
    productionWindow: "3 a 5 dias",
    imageHint: "Topo de Bolo Personalizado",
    image: "/catalog-assets/product-39.jpg",
    images: ["/catalog-assets/product-39.jpg", "/catalog-assets/product-39-2.jpg", "/catalog-assets/product-39-3.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 18,
    dimensions: "14x10x0.3cm",
    customizable: true,
  },
  {
    id: "mdh-040",
    sku: "MDH-0040",
    name: "Imã Frase Geek",
    category: "Presentes Criativos",
    subcategory: "Imã",
    theme: "Imã",
    collection: "Pronta entrega",
    colors: ["Preto", "Branco", "Verde"],
    grams: 14,
    hours: 0.6,
    complexity: 1.09,
    featured: false,
    description: "Pensado para surpreender com personalização rápida e acabamento bonito de verdade. Produzido em PLA Premium com acabamento premium e revisão antes do envio. Uma opção forte para presentes criativos feitos no RJ com atendimento humano.",
    tags: ["imã", "geladeira", "geek"],
    pricePix: 13.9,
    priceCard: 15.9,
    marketplaceSuggested: 17.81,
    productionWindow: "24h a 48h",
    imageHint: "Imã Frase Geek",
    image: "/catalog-assets/product-40.jpg",
    images: ["/catalog-assets/product-40.jpg", "/catalog-assets/product-40-2.jpg", "/catalog-assets/product-40-3.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Pronta entrega",
    stock: 30,
    dimensions: "6x6x0.6cm",
    customizable: true,
  },
  {
    id: "mdh-041",
    sku: "MDH-0041",
    name: "Porta-Copos Pixel Kit",
    category: "Presentes Criativos",
    subcategory: "Porta-copos",
    theme: "Porta-copos",
    collection: "Pronta entrega",
    colors: ["Preto", "Cinza", "Vermelho"],
    grams: 46,
    hours: 1.8,
    complexity: 1.29,
    featured: false,
    description: "Pensado para surpreender com personalização rápida e acabamento bonito de verdade. Produzido em PLA Premium com acabamento premium e revisão antes do envio. Uma opção forte para presentes criativos feitos no RJ com atendimento humano.",
    tags: ["porta-copos", "kit", "casa"],
    pricePix: 24.9,
    priceCard: 28.9,
    marketplaceSuggested: 32.37,
    productionWindow: "24h a 48h",
    imageHint: "Porta-Copos Pixel Kit",
    image: "/catalog-assets/product-41.jpg",
    images: ["/catalog-assets/product-41.jpg", "/catalog-assets/product-41-2.jpg", "/catalog-assets/product-41-3.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Pronta entrega",
    stock: 16,
    dimensions: "9x9x0.8cm",
    customizable: false,
  },
  {
    id: "mdh-042",
    sku: "MDH-0042",
    name: "Luminária Nome LED",
    category: "Presentes Criativos",
    subcategory: "Luminária",
    theme: "Luminária",
    collection: "Sob encomenda",
    colors: ["Branco", "Preto", "Azul"],
    grams: 148,
    hours: 5.8,
    complexity: 1.95,
    featured: true,
    description: "Pensado para surpreender com personalização rápida e acabamento bonito de verdade. Produzido em PLA Premium com acabamento premium e revisão antes do envio. Uma opção forte para presentes criativos feitos no RJ com atendimento humano.",
    tags: ["led", "nome", "presente"],
    pricePix: 89.9,
    priceCard: 102.9,
    marketplaceSuggested: 115.25,
    productionWindow: "5 a 7 dias",
    imageHint: "Luminária Nome LED",
    image: "/catalog-assets/product-42.jpg",
    images: ["/catalog-assets/product-42.jpg", "/catalog-assets/product-42-2.jpg", "/catalog-assets/product-42-3.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 5,
    dimensions: "22x5x16cm",
    customizable: true,
  },
  {
    id: "mdh-043",
    sku: "MDH-0043",
    name: "Foto Litofania Frame",
    category: "Presentes Criativos",
    subcategory: "Litofania",
    theme: "Litofania",
    collection: "Sob encomenda",
    colors: ["Branco"],
    grams: 132,
    hours: 6.1,
    complexity: 1.94,
    featured: true,
    description: "Pensado para surpreender com personalização rápida e acabamento bonito de verdade. Produzido em PLA Premium com acabamento premium e revisão antes do envio. Uma opção forte para presentes criativos feitos no RJ com atendimento humano.",
    tags: ["foto", "presente", "emocional"],
    pricePix: 94.9,
    priceCard: 108.9,
    marketplaceSuggested: 121.97,
    productionWindow: "5 a 7 dias",
    imageHint: "Foto Litofania Frame",
    image: "/catalog-assets/product-43.jpg",
    images: ["/catalog-assets/product-43.jpg", "/catalog-assets/product-43-2.jpg", "/catalog-assets/product-43-3.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 4,
    dimensions: "14x10x16cm",
    customizable: true,
  },
  {
    id: "mdh-044",
    sku: "MDH-0044",
    name: "Mini Troféu Personalizado",
    category: "Presentes Criativos",
    subcategory: "Brinde",
    theme: "Brinde",
    collection: "Sob encomenda",
    colors: ["Dourado", "Prata", "Branco"],
    grams: 54,
    hours: 2.3,
    complexity: 1.36,
    featured: false,
    description: "Pensado para surpreender com personalização rápida e acabamento bonito de verdade. Produzido em PLA Silk com acabamento premium e revisão antes do envio. Uma opção forte para presentes criativos feitos no RJ com atendimento humano.",
    tags: ["troféu", "evento", "empresa"],
    pricePix: 34.9,
    priceCard: 39.9,
    marketplaceSuggested: 44.69,
    productionWindow: "3 a 5 dias",
    imageHint: "Mini Troféu Personalizado",
    image: "/catalog-assets/product-44.jpg",
    images: ["/catalog-assets/product-44.jpg", "/catalog-assets/product-44-2.jpg", "/catalog-assets/product-44-3.jpg"],
    material: "PLA Silk",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 10,
    dimensions: "9x9x13cm",
    customizable: true,
  },
  {
    id: "mdh-045",
    sku: "MDH-0045",
    name: "Tag Mochila Personal",
    category: "Presentes Criativos",
    subcategory: "Tag",
    theme: "Tag",
    collection: "Pronta entrega",
    colors: ["Azul", "Rosa", "Preto"],
    grams: 10,
    hours: 0.4,
    complexity: 1.06,
    featured: false,
    description: "Pensado para surpreender com personalização rápida e acabamento bonito de verdade. Produzido em PLA Premium com acabamento premium e revisão antes do envio. Uma opção forte para presentes criativos feitos no RJ com atendimento humano.",
    tags: ["mochila", "tag", "personalizado"],
    pricePix: 11.9,
    priceCard: 13.9,
    marketplaceSuggested: 15.57,
    productionWindow: "24h a 48h",
    imageHint: "Tag Mochila Personal",
    image: "/catalog-assets/product-45.jpg",
    images: ["/catalog-assets/product-45.jpg", "/catalog-assets/product-45-2.jpg", "/catalog-assets/product-45-3.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Pronta entrega",
    stock: 36,
    dimensions: "6x4x0.4cm",
    customizable: true,
  },
  {
    id: "mdh-046",
    sku: "MDH-0046",
    name: "Kit Chaveiro + Imã",
    category: "Presentes Criativos",
    subcategory: "Kit",
    theme: "Kit",
    collection: "Pronta entrega",
    colors: ["Sortidas"],
    grams: 24,
    hours: 0.9,
    complexity: 1.15,
    featured: false,
    description: "Pensado para surpreender com personalização rápida e acabamento bonito de verdade. Produzido em PLA Premium com acabamento premium e revisão antes do envio. Uma opção forte para presentes criativos feitos no RJ com atendimento humano.",
    tags: ["kit", "lembrança", "gift"],
    pricePix: 18.9,
    priceCard: 21.9,
    marketplaceSuggested: 24.53,
    productionWindow: "24h a 48h",
    imageHint: "Kit Chaveiro + Imã",
    image: "/catalog-assets/product-46.jpg",
    images: ["/catalog-assets/product-46.jpg", "/catalog-assets/product-46-2.jpg", "/catalog-assets/product-46-3.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Pronta entrega",
    stock: 22,
    dimensions: "kit",
    customizable: true,
  },
  {
    id: "mdh-047",
    sku: "MDH-0047",
    name: "Marcador de Página 3D",
    category: "Presentes Criativos",
    subcategory: "Acessório",
    theme: "Acessório",
    collection: "Pronta entrega",
    colors: ["Preto", "Roxo", "Azul"],
    grams: 9,
    hours: 0.3,
    complexity: 1.05,
    featured: false,
    description: "Pensado para surpreender com personalização rápida e acabamento bonito de verdade. Produzido em PLA Premium com acabamento premium e revisão antes do envio. Uma opção forte para presentes criativos feitos no RJ com atendimento humano.",
    tags: ["livro", "presente", "criativo"],
    pricePix: 10.9,
    priceCard: 12.9,
    marketplaceSuggested: 14.45,
    productionWindow: "24h a 48h",
    imageHint: "Marcador de Página 3D",
    image: "/catalog-assets/product-47.jpg",
    images: ["/catalog-assets/product-47.jpg", "/catalog-assets/product-47-2.jpg", "/catalog-assets/product-47-3.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Pronta entrega",
    stock: 28,
    dimensions: "15x4x0.2cm",
    customizable: true,
  },
  {
    id: "mdh-048",
    sku: "MDH-0048",
    name: "Caixa Presente Modular",
    category: "Presentes Criativos",
    subcategory: "Embalagem",
    theme: "Embalagem",
    collection: "Lançamentos",
    colors: ["Vermelho", "Preto", "Branco"],
    grams: 102,
    hours: 3.9,
    complexity: 1.65,
    featured: false,
    description: "Pensado para surpreender com personalização rápida e acabamento bonito de verdade. Produzido em PLA Premium com acabamento premium e revisão antes do envio. Uma opção forte para presentes criativos feitos no RJ com atendimento humano.",
    tags: ["caixa", "presente", "decoração"],
    pricePix: 44.9,
    priceCard: 51.9,
    marketplaceSuggested: 58.13,
    productionWindow: "3 a 5 dias",
    imageHint: "Caixa Presente Modular",
    image: "/catalog-assets/product-48.jpg",
    images: ["/catalog-assets/product-48.jpg", "/catalog-assets/product-48-2.jpg", "/catalog-assets/product-48-3.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 8,
    dimensions: "12x12x10cm",
    customizable: true,
  },
  {
    id: "mdh-049",
    sku: "MDH-0049",
    name: "Logo de Empresa Desk Sign",
    category: "Sob Encomenda",
    subcategory: "Corporativo",
    theme: "Corporativo",
    collection: "Sob encomenda",
    colors: ["Branco", "Preto", "Azul"],
    grams: 118,
    hours: 4.8,
    complexity: 1.77,
    featured: false,
    description: "Projeto sob medida para quem precisa de peça funcional, decorativa ou corporativa com briefing alinhado. Produção local no Rio de Janeiro em PLA Premium, com validação visual e acompanhamento próximo pelo WhatsApp. Ideal para pedidos personalizados e pequenas séries.",
    tags: ["logo", "empresa", "branding"],
    pricePix: 79.9,
    priceCard: 91.9,
    marketplaceSuggested: 102.93,
    productionWindow: "5 a 7 dias",
    imageHint: "Logo de Empresa Desk Sign",
    image: "/catalog-assets/product-49.jpg",
    images: ["/catalog-assets/product-49.jpg", "/catalog-assets/product-49-2.jpg", "/catalog-assets/product-49-3.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 6,
    dimensions: "24x3x12cm",
    customizable: true,
  },
  {
    id: "mdh-050",
    sku: "MDH-0050",
    name: "Placa QR Code de Mesa",
    category: "Sob Encomenda",
    subcategory: "Comercial",
    theme: "Comercial",
    collection: "Sob encomenda",
    colors: ["Branco", "Preto"],
    grams: 34,
    hours: 1.4,
    complexity: 1.22,
    featured: false,
    description: "Projeto sob medida para quem precisa de peça funcional, decorativa ou corporativa com briefing alinhado. Produção local no Rio de Janeiro em PLA Premium, com validação visual e acompanhamento próximo pelo WhatsApp. Ideal para pedidos personalizados e pequenas séries.",
    tags: ["qr code", "negócio", "mesa"],
    pricePix: 24.9,
    priceCard: 28.9,
    marketplaceSuggested: 32.37,
    productionWindow: "3 a 5 dias",
    imageHint: "Placa QR Code de Mesa",
    image: "/catalog-assets/product-50.jpg",
    images: ["/catalog-assets/product-50.jpg", "/catalog-assets/product-50-2.jpg", "/catalog-assets/product-50-3.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 14,
    dimensions: "10x8x4cm",
    customizable: true,
  },
  {
    id: "mdh-051",
    sku: "MDH-0051",
    name: "Display para Produto Vitrine",
    category: "Sob Encomenda",
    subcategory: "Display",
    theme: "Display",
    collection: "Sob encomenda",
    colors: ["Preto", "Branco", "Translúcido"],
    grams: 92,
    hours: 3.6,
    complexity: 1.59,
    featured: false,
    description: "Projeto sob medida para quem precisa de peça funcional, decorativa ou corporativa com briefing alinhado. Produção local no Rio de Janeiro em PETG, com validação visual e acompanhamento próximo pelo WhatsApp. Ideal para pedidos personalizados e pequenas séries.",
    tags: ["vitrine", "produto", "loja"],
    pricePix: 54.9,
    priceCard: 62.9,
    marketplaceSuggested: 70.45,
    productionWindow: "5 a 7 dias",
    imageHint: "Display para Produto Vitrine",
    image: "/catalog-assets/product-51.jpg",
    images: ["/catalog-assets/product-51.jpg", "/catalog-assets/product-51-2.jpg", "/catalog-assets/product-51-3.jpg"],
    material: "PETG",
    finish: "Técnico",
    status: "Sob encomenda",
    stock: 8,
    dimensions: "18x12x10cm",
    customizable: true,
  },
  {
    id: "mdh-052",
    sku: "MDH-0052",
    name: "Organizador Ferramenta Maker",
    category: "Sob Encomenda",
    subcategory: "Oficina",
    theme: "Oficina",
    collection: "Sob encomenda",
    colors: ["Preto", "Laranja"],
    grams: 146,
    hours: 5.7,
    complexity: 1.94,
    featured: false,
    description: "Projeto sob medida para quem precisa de peça funcional, decorativa ou corporativa com briefing alinhado. Produção local no Rio de Janeiro em PETG, com validação visual e acompanhamento próximo pelo WhatsApp. Ideal para pedidos personalizados e pequenas séries.",
    tags: ["maker", "ferramenta", "oficina"],
    pricePix: 68.9,
    priceCard: 78.9,
    marketplaceSuggested: 88.37,
    productionWindow: "5 a 7 dias",
    imageHint: "Organizador Ferramenta Maker",
    image: "/catalog-assets/product-52.jpg",
    images: ["/catalog-assets/product-52.jpg", "/catalog-assets/product-52-2.jpg", "/catalog-assets/product-52-3.jpg"],
    material: "PETG",
    finish: "Técnico",
    status: "Sob encomenda",
    stock: 5,
    dimensions: "20x15x8cm",
    customizable: true,
  },
  {
    id: "mdh-053",
    sku: "MDH-0053",
    name: "Case Controle Sob Medida",
    category: "Sob Encomenda",
    subcategory: "Case",
    theme: "Case",
    collection: "Sob encomenda",
    colors: ["Preto", "Cinza"],
    grams: 156,
    hours: 6.0,
    complexity: 1.99,
    featured: false,
    description: "Projeto sob medida para quem precisa de peça funcional, decorativa ou corporativa com briefing alinhado. Produção local no Rio de Janeiro em PETG, com validação visual e acompanhamento próximo pelo WhatsApp. Ideal para pedidos personalizados e pequenas séries.",
    tags: ["case", "controle", "transporte"],
    pricePix: 72.9,
    priceCard: 83.9,
    marketplaceSuggested: 93.97,
    productionWindow: "5 a 7 dias",
    imageHint: "Case Controle Sob Medida",
    image: "/catalog-assets/product-53.jpg",
    images: ["/catalog-assets/product-53.jpg", "/catalog-assets/product-53-2.jpg", "/catalog-assets/product-53-3.jpg"],
    material: "PETG",
    finish: "Técnico",
    status: "Sob encomenda",
    stock: 4,
    dimensions: "24x16x9cm",
    customizable: true,
  },
  {
    id: "mdh-054",
    sku: "MDH-0054",
    name: "Placa de Porta Personalizada",
    category: "Sob Encomenda",
    subcategory: "Sinalização",
    theme: "Sinalização",
    collection: "Sob encomenda",
    colors: ["Preto", "Branco", "Madeira"],
    grams: 48,
    hours: 1.9,
    complexity: 1.31,
    featured: false,
    description: "Projeto sob medida para quem precisa de peça funcional, decorativa ou corporativa com briefing alinhado. Produção local no Rio de Janeiro em PLA Premium, com validação visual e acompanhamento próximo pelo WhatsApp. Ideal para pedidos personalizados e pequenas séries.",
    tags: ["porta", "nome", "decoração"],
    pricePix: 29.9,
    priceCard: 33.9,
    marketplaceSuggested: 37.97,
    productionWindow: "3 a 5 dias",
    imageHint: "Placa de Porta Personalizada",
    image: "/catalog-assets/product-54.jpg",
    images: ["/catalog-assets/product-54.jpg", "/catalog-assets/product-54-2.jpg", "/catalog-assets/product-54-3.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 12,
    dimensions: "18x8x0.5cm",
    customizable: true,
  },
  {
    id: "mdh-055",
    sku: "MDH-0055",
    name: "Mini Maquete Conceitual",
    category: "Sob Encomenda",
    subcategory: "Arquitetura",
    theme: "Arquitetura",
    collection: "Sob encomenda",
    colors: ["Branco", "Cinza"],
    grams: 170,
    hours: 7.0,
    complexity: 2.12,
    featured: false,
    description: "Projeto sob medida para quem precisa de peça funcional, decorativa ou corporativa com briefing alinhado. Produção local no Rio de Janeiro em PLA Premium, com validação visual e acompanhamento próximo pelo WhatsApp. Ideal para pedidos personalizados e pequenas séries.",
    tags: ["maquete", "arquitetura", "modelo"],
    pricePix: 96.9,
    priceCard: 111.9,
    marketplaceSuggested: 125.33,
    productionWindow: "5 a 7 dias",
    imageHint: "Mini Maquete Conceitual",
    image: "/catalog-assets/product-55.jpg",
    images: ["/catalog-assets/product-55.jpg", "/catalog-assets/product-55-2.jpg", "/catalog-assets/product-55-3.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 3,
    dimensions: "18x18x10cm",
    customizable: true,
  },
  {
    id: "mdh-056",
    sku: "MDH-0056",
    name: "Suporte Técnico sob Medida",
    category: "Sob Encomenda",
    subcategory: "Funcional",
    theme: "Funcional",
    collection: "Sob encomenda",
    colors: ["Preto", "Cinza"],
    grams: 88,
    hours: 3.4,
    complexity: 1.56,
    featured: false,
    description: "Projeto sob medida para quem precisa de peça funcional, decorativa ou corporativa com briefing alinhado. Produção local no Rio de Janeiro em PETG, com validação visual e acompanhamento próximo pelo WhatsApp. Ideal para pedidos personalizados e pequenas séries.",
    tags: ["técnico", "adaptador", "medida"],
    pricePix: 46.9,
    priceCard: 53.9,
    marketplaceSuggested: 60.37,
    productionWindow: "3 a 5 dias",
    imageHint: "Suporte Técnico sob Medida",
    image: "/catalog-assets/product-56.jpg",
    images: ["/catalog-assets/product-56.jpg", "/catalog-assets/product-56-2.jpg", "/catalog-assets/product-56-3.jpg"],
    material: "PETG",
    finish: "Técnico",
    status: "Sob encomenda",
    stock: 9,
    dimensions: "sob medida",
    customizable: true,
  },
  {
    id: "mdh-057",
    sku: "MDH-0057",
    name: "Brinde Evento em Lote",
    category: "Sob Encomenda",
    subcategory: "Eventos",
    theme: "Eventos",
    collection: "Sob encomenda",
    colors: ["Sortidas"],
    grams: 16,
    hours: 0.6,
    complexity: 1.1,
    featured: false,
    description: "Projeto sob medida para quem precisa de peça funcional, decorativa ou corporativa com briefing alinhado. Produção local no Rio de Janeiro em PLA Premium, com validação visual e acompanhamento próximo pelo WhatsApp. Ideal para pedidos personalizados e pequenas séries.",
    tags: ["evento", "lote", "brinde"],
    pricePix: 9.9,
    priceCard: 11.9,
    marketplaceSuggested: 13.33,
    productionWindow: "5 a 7 dias",
    imageHint: "Brinde Evento em Lote",
    image: "/catalog-assets/product-57.jpg",
    images: ["/catalog-assets/product-57.jpg", "/catalog-assets/product-57-2.jpg", "/catalog-assets/product-57-3.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 100,
    dimensions: "5x5x0.5cm",
    customizable: true,
  },
  {
    id: "mdh-058",
    sku: "MDH-0058",
    name: "Litofania Luminosa Premium",
    category: "Sob Encomenda",
    subcategory: "Litofania",
    theme: "Litofania",
    collection: "Sob encomenda",
    colors: ["Branco"],
    grams: 158,
    hours: 6.8,
    complexity: 2.08,
    featured: true,
    description: "Projeto sob medida para quem precisa de peça funcional, decorativa ou corporativa com briefing alinhado. Produção local no Rio de Janeiro em PLA Premium, com validação visual e acompanhamento próximo pelo WhatsApp. Ideal para pedidos personalizados e pequenas séries.",
    tags: ["litofania", "premium", "foto"],
    pricePix: 109.9,
    priceCard: 124.9,
    marketplaceSuggested: 139.89,
    productionWindow: "5 a 7 dias",
    imageHint: "Litofania Luminosa Premium",
    image: "/catalog-assets/product-58.jpg",
    images: ["/catalog-assets/product-58.jpg", "/catalog-assets/product-58-2.jpg", "/catalog-assets/product-58-3.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 3,
    dimensions: "16x12x18cm",
    customizable: true,
  },
  {
    id: "mdh-059",
    sku: "MDH-0059",
    name: "Suporte Camera Custom",
    category: "Sob Encomenda",
    subcategory: "Acessório",
    theme: "Acessório",
    collection: "Sob encomenda",
    colors: ["Preto"],
    grams: 64,
    hours: 2.6,
    complexity: 1.42,
    featured: false,
    description: "Projeto sob medida para quem precisa de peça funcional, decorativa ou corporativa com briefing alinhado. Produção local no Rio de Janeiro em PETG, com validação visual e acompanhamento próximo pelo WhatsApp. Ideal para pedidos personalizados e pequenas séries.",
    tags: ["camera", "fixação", "custom"],
    pricePix: 38.9,
    priceCard: 44.9,
    marketplaceSuggested: 50.29,
    productionWindow: "3 a 5 dias",
    imageHint: "Suporte Camera Custom",
    image: "/catalog-assets/product-59.jpg",
    images: ["/catalog-assets/product-59.jpg", "/catalog-assets/product-59-2.jpg", "/catalog-assets/product-59-3.jpg"],
    material: "PETG",
    finish: "Técnico",
    status: "Sob encomenda",
    stock: 8,
    dimensions: "sob medida",
    customizable: true,
  },
  {
    id: "mdh-060",
    sku: "MDH-0060",
    name: "Luminária Corporativa LED",
    category: "Sob Encomenda",
    subcategory: "Corporativo",
    theme: "Corporativo",
    collection: "Lançamentos",
    colors: ["Branco", "Azul"],
    grams: 188,
    hours: 7.4,
    complexity: 2.21,
    featured: true,
    description: "Projeto sob medida para quem precisa de peça funcional, decorativa ou corporativa com briefing alinhado. Produção local no Rio de Janeiro em PLA Premium, com validação visual e acompanhamento próximo pelo WhatsApp. Ideal para pedidos personalizados e pequenas séries.",
    tags: ["led", "corporativo", "branding"],
    pricePix: 119.9,
    priceCard: 136.9,
    marketplaceSuggested: 153.33,
    productionWindow: "5 a 7 dias",
    imageHint: "Luminária Corporativa LED",
    image: "/catalog-assets/product-60.jpg",
    images: ["/catalog-assets/product-60.jpg", "/catalog-assets/product-60-2.jpg", "/catalog-assets/product-60-3.jpg"],
    material: "PLA Premium",
    finish: "Premium",
    status: "Sob encomenda",
    stock: 3,
    dimensions: "26x5x18cm",
    customizable: true,
  },
];

export const catalog = curatedCatalog;
export const featuredCatalog = curatedCatalog.filter((item) => item.featured).slice(0, 12);
export const categories = Array.from(new Set(curatedCatalog.map((item) => item.category)));
export const collections = Array.from(new Set(curatedCatalog.map((item) => item.collection)));

export function getProductUrl(product: Product) {
  return `/catalogo/${product.id}-${slugify(product.name)}`;
}

export function findProduct(id: string) {
  return curatedCatalog.find((item) => item.id === id);
}

export function findProductBySlug(slug: string) {
  return curatedCatalog.find((item) => getProductUrl(item).endsWith(slug));
}

export function searchCatalog(query: string) {
  const normalized = query.trim().toLowerCase();
  if (!normalized) return curatedCatalog;
  return curatedCatalog.filter((item) =>
    [item.name, item.category, item.subcategory, item.theme, item.description, item.collection, item.material, item.finish, ...item.tags]
      .join(" ")
      .toLowerCase()
      .includes(normalized)
  );
}

export const defaultPricingExamples = [
  { title: "Chibi premium", grams: 32, hours: 1.9, complexity: 1.1 },
  { title: "Suporte de controle", grams: 92, hours: 3.2, complexity: 1.35 },
  { title: "Vaso geométrico", grams: 96, hours: 3.8, complexity: 1.4 },
  { title: "Nome 3D personalizado", grams: 86, hours: 3.2, complexity: 1.3 },
].map((item) => ({
  ...item,
  pricePix: calculateSalePrice(item.grams, item.hours, item.complexity, "pix", "site"),
  priceCard: calculateSalePrice(item.grams, item.hours, item.complexity, "cartao", "site"),
}));

export const deliverySummary = [...deliveryZones];