services:
  app:
    extends:
      file: docker-compose.yml
      service: app
  postgres:
    extends:
      file: docker-compose.yml
      service: postgres
  redis:
    extends:
      file: docker-compose.yml
      service: redis
  mailhog:
    extends:
      file: docker-compose.yml
      service: mailhog
