export type ProductionStage = "recebido" | "imprimindo" | "pronto";
export type ProfitMode = "margin" | "markup";
export type TaxonomyConfidence = "high" | "medium" | "low";

export type AdminProductOverride = {
  id: string;
  title?: string;
  description?: string;
  category?: string;
  subcategory?: string;
  collection?: string;
  material?: string;
  finish?: string;
  tags?: string[];
  primaryCategory?: string;
  productTypePath?: string;
  buyingIntents?: string[];
  objectType?: string;
  useCaseTags?: string[];
  seoKeywords?: string[];
  confidence?: TaxonomyConfidence;
  classificationReason?: string;
  taxonomyReviewRequested?: boolean;
  status?: "Pronta entrega" | "Sob encomenda";
  stock?: number;
  readyToShip?: boolean;
  customizable?: boolean;
  featured?: boolean;
  costBase?: number;
  pricePix?: number;
  priceCard?: number;
  estimatedGrams?: number;
  estimatedHours?: number;
  complexity?: number;
  spoolPricePerKg?: number;
  machineHourlyRate?: number;
  postProcessMinutes?: number;
  laborHourlyRate?: number;
  packagingCost?: number;
  overheadPercent?: number;
  profitMode?: ProfitMode;
  profitTargetPercent?: number;
  estimatedProfitAmount?: number;
  estimatedProfitPercent?: number;
  costingUpdatedAt?: string;
  productionStage?: ProductionStage;
  updatedAt?: string;
};

export type RealImageStatusRecord = {
  status: "real";
  sourceType: string;
  sourceCount: number;
  updatedAt: string;
  gallery: string[];
  notes?: string;
};
