/**
 * Media Validation System
 *
 * Enforces the "Golden Rule": no image is used publicly unless it passes
 * semantic correspondence checks or is explicitly verified.
 *
 * Status hierarchy (strictest to most permissive):
 *   verified        → full public use, hero-eligible
 *   render-verified → from real 3D model, public use, hero-eligible
 *   probable        → high semantic match, public with "imagem ilustrativa" note
 *   needs_review    → queued for manual review, blocked from hero
 *   placeholder     → generic/fallback, shown only with honest UX treatment
 *   rejected        → flagged wrong, never shown
 */

import type { Product } from "@/lib/catalog";
import type { CatalogPhotoKind } from "@/lib/catalog-photo-manifest";
import { getCatalogPhotoEntry } from "@/lib/catalog-photo-manifest";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type MediaVerificationStatus =
  | "verified"
  | "render-verified"
  | "probable"
  | "needs_review"
  | "placeholder"
  | "rejected";

export interface ProductMediaRecord {
  productId: string;
  status: MediaVerificationStatus;
  heroImage: string | null;
  gallery: ProductImageEntry[];
  reviewNote?: string;
  lastAuditedAt?: string;
}

export interface ProductImageEntry {
  url: string;
  alt: string;
  sortOrder: number;
  sourceType: "internal-photo" | "render-3d" | "ai-generated" | "external-sourced" | "placeholder" | "unknown";
  verificationStatus: MediaVerificationStatus;
  aspectRatio?: string;
  width?: number;
  height?: number;
  caption?: string;
  usageHint?: "hero" | "gallery" | "detail" | "context" | "scale";
}

// ---------------------------------------------------------------------------
// Semantic matching helpers
// ---------------------------------------------------------------------------

function normalizeText(text: string): string {
  return text
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9\s]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function extractKeywords(text: string): Set<string> {
  const stopWords = new Set([
    "de", "da", "do", "das", "dos", "em", "no", "na", "nos", "nas",
    "com", "para", "por", "que", "uma", "um", "se", "ou", "e",
    "a", "o", "as", "os", "the", "of", "and", "for", "in", "with",
  ]);
  const words = normalizeText(text).split(" ");
  return new Set(words.filter((w) => w.length > 2 && !stopWords.has(w)));
}

export function computeSemanticScore(product: Product, filename: string): number {
  const nameKw = extractKeywords(product.name);
  const descKw = extractKeywords(product.description);
  const catKw = extractKeywords(product.category);
  const tagKw = new Set(product.tags.flatMap((t) => [...extractKeywords(t)]));
  const fileKw = extractKeywords(filename.replace(/\.(webp|jpg|png|jpeg)$/i, "").replace(/[-_]/g, " "));

  const allProductKw = new Set([...nameKw, ...descKw, ...catKw, ...tagKw]);

  let score = 0;
  let maxScore = 0;

  // Name match is highest priority (40%)
  for (const kw of nameKw) {
    maxScore += 40;
    if (fileKw.has(kw)) score += 40;
  }

  // Category match (20%)
  for (const kw of catKw) {
    maxScore += 20;
    if (fileKw.has(kw)) score += 20;
  }

  // Tag match (20%)
  for (const kw of tagKw) {
    maxScore += 20;
    if (fileKw.has(kw)) score += 20;
  }

  // Description match (20%)
  for (const kw of descKw) {
    maxScore += 20;
    if (fileKw.has(kw)) score += 20;
  }

  // Product ID in filename (bonus)
  if (fileKw.has(product.id.replace(/-/g, " ").trim()) || filename.includes(product.id)) {
    score += 30;
    maxScore += 30;
  }

  return maxScore > 0 ? Math.round((score / maxScore) * 100) : 0;
}

// ---------------------------------------------------------------------------
// Status derivation
// ---------------------------------------------------------------------------

/**
 * IDs confirmed BLOCKED by the semantic audit — their 4-image sets are
 * placeholder text cards (gradient backgrounds with rendered text), NOT
 * actual product photographs. This list is regenerated by
 * scripts/catalog_semantic_audit.mjs and must NOT be bypassed.
 */
import semanticAuditData from "../output/CATALOG_SEMANTIC_AUDIT.json";

const _semanticBlocklist: Set<string> = new Set(
  (
    semanticAuditData as {
      items: Array<{ id: string; status: string; isPlaceholderSet: boolean }>;
    }
  ).items
    .filter((i) => i.status === "BLOCKED" || i.isPlaceholderSet)
    .map((i) => i.id),
);

export function deriveMediaStatus(
  product: Product,
  photoKind: CatalogPhotoKind | undefined,
  semanticScore: number,
): MediaVerificationStatus {
  // foto-real from verified sources → always verified.
  // This check MUST come before the blocklist because the blocklist may contain
  // stale audit entries that were generated when the product had different (placeholder)
  // images. Once a product is reclassified as "foto-real" in the manifest it is verified.
  if (photoKind === "foto-real") return "verified";

  // render from real 3D model → render-verified (also precedes blocklist)
  if (photoKind === "render-fiel") return "render-verified";

  // HARD BLOCK: items whose image sets are placeholder text cards (conceptual only)
  if (_semanticBlocklist.has(product.id)) return "placeholder";

  // imagem-conceitual with near-perfect semantic match → probable
  if (photoKind === "imagem-conceitual" && semanticScore >= 99) return "probable";

  // imagem-conceitual with partial match → needs_review
  if (photoKind === "imagem-conceitual" && semanticScore >= 80) return "needs_review";

  // Very low score → placeholder
  if (photoKind === "imagem-conceitual") return "placeholder";

  // No entry → placeholder
  return "placeholder";
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export function validateProductMedia(product: Product): ProductMediaRecord {
  const catalogEntry = getCatalogPhotoEntry(product.id);
  const photoKind = catalogEntry?.kind;
  const primaryImage = product.images?.[0] || (product as Product & { image?: string }).image || null;

  const semanticScore = primaryImage
    ? computeSemanticScore(product, primaryImage)
    : 0;

  const status = deriveMediaStatus(product, photoKind, semanticScore);

  const gallery: ProductImageEntry[] = (product.images || []).map((url, i) => ({
    url,
    alt: i === 0
      ? `Impressão 3D de ${product.name} — ${product.material}, ${product.finish} — MDH 3D Store`
      : `Impressão 3D de ${product.name} — ângulo ${i + 1} — MDH 3D Store`,
    sortOrder: i,
    sourceType: inferSourceType(url, photoKind),
    verificationStatus: i === 0 ? status : deriveGalleryItemStatus(status),
    usageHint: i === 0 ? "hero" : i === 1 ? "gallery" : i === 2 ? "detail" : "context",
  }));
  const galleryReady = gallery.length >= 4;
  const hasVerifiedHeroStatus = status === "verified" || status === "render-verified";
  const heroEligible = isHeroEligible(status, gallery.length);

  return {
    productId: product.id,
    status,
    heroImage: heroEligible ? (primaryImage ?? null) : null,
    gallery,
    reviewNote: status === "needs_review"
      ? `Semantic score ${semanticScore}% — image may not match "${product.name}". Manual review required.`
      : status === "placeholder"
        ? `Image is a generic placeholder/AI-generated conceptual. Does not represent the actual product.`
        : hasVerifiedHeroStatus && !galleryReady
          ? `Gallery has ${gallery.length}/4 images. Add more verified photos to reach 4-image target.`
          : undefined,
    lastAuditedAt: new Date().toISOString(),
  };
}

export function isHeroEligible(status: MediaVerificationStatus, imageCount = 0): boolean {
  // Verified and render-verified products are hero-eligible as long as at least one
  // validated image exists.  The previous requirement of ≥ 4 images was a future-state
  // goal that was incorrectly used as a hard gate, blocking legitimate products that have
  // 3 high-quality real photos but no 4th.
  return (status === "verified" || status === "render-verified") && imageCount >= 1;
}

export function isPublicSafe(status: MediaVerificationStatus): boolean {
  return status === "verified" || status === "render-verified" || status === "probable";
}

function inferSourceType(url: string, photoKind?: CatalogPhotoKind): ProductImageEntry["sourceType"] {
  if (url.includes("/products/foto-") || url.includes("/products/real-")) return "internal-photo";
  if (url.includes("/products/render-")) return "render-3d";
  if (url.includes("/products/a1-mini-expansion/")) return "render-3d";
  if (url.includes("/products/csv-curated/")) return "external-sourced";
  if (url.includes("/catalog-assets/product-placeholder")) return "placeholder";
  if (photoKind === "foto-real") return "internal-photo";
  if (photoKind === "render-fiel") return "render-3d";
  return "ai-generated";
}

function deriveGalleryItemStatus(heroStatus: MediaVerificationStatus): MediaVerificationStatus {
  // Gallery variants inherit from hero, but never higher than "probable"
  if (heroStatus === "verified" || heroStatus === "render-verified") return heroStatus;
  return heroStatus;
}

// ---------------------------------------------------------------------------
// Bulk audit helper
// ---------------------------------------------------------------------------

export interface CatalogMediaAuditResult {
  total: number;
  verified: number;
  renderVerified: number;
  probable: number;
  needsReview: number;
  placeholder: number;
  rejected: number;
  items: ProductMediaRecord[];
}

export function auditCatalogMedia(products: Product[]): CatalogMediaAuditResult {
  const items = products.map(validateProductMedia);
  return {
    total: items.length,
    verified: items.filter((i) => i.status === "verified").length,
    renderVerified: items.filter((i) => i.status === "render-verified").length,
    probable: items.filter((i) => i.status === "probable").length,
    needsReview: items.filter((i) => i.status === "needs_review").length,
    placeholder: items.filter((i) => i.status === "placeholder").length,
    rejected: items.filter((i) => i.status === "rejected").length,
    items,
  };
}
