import { Product } from "./catalog";

export const professionalCatalogData: Partial<Product>[] = [
  {
    id: "mdh-a1-001",
    sku: "MDH-A1-001",
    name: "Suporte Headset Arc",
    category: "Setup & Organização",
    collection: "A1 Mini Validada",
    material: "PLA",
    finish: "Matte",
    productionWindow: "24h",
    status: "Pronta entrega",
    grams: 85,
    hours: 3.5,
    complexity: 1.2,
    pricePix: 69.90,
    priceCard: 79.90,
    description: "Suporte ergonômico e minimalista para fones de ouvido, garantindo organização e estilo para seu setup.",
    tags: ["setup", "organização", "headset"],
    featured: true,
    readyToShip: true,
    stock: 10,
    dimensions: "12x10x22cm"
  },
  {
    id: "mdh-a1-002",
    sku: "MDH-A1-002",
    name: "Dock Controle Solo",
    category: "Setup & Organização",
    collection: "A1 Mini Validada",
    material: "PLA",
    finish: "Matte",
    productionWindow: "24h",
    status: "Pronta entrega",
    grams: 65,
    hours: 2.8,
    complexity: 1.15,
    pricePix: 49.90,
    priceCard: 56.90,
    description: "Base estável para controles de console (PS5, Xbox, Switch), mantendo sua mesa livre de bagunça.",
    tags: ["gaming", "setup", "controle"],
    featured: true,
    readyToShip: true,
    stock: 15,
    dimensions: "10x8x6cm"
  },
  {
    id: "mdh-a1-003",
    sku: "MDH-A1-003",
    name: "Base Celular Tilt",
    category: "Setup & Organização",
    collection: "A1 Mini Validada",
    material: "PLA",
    finish: "Matte",
    productionWindow: "24h",
    status: "Pronta entrega",
    grams: 45,
    hours: 1.5,
    complexity: 1.1,
    pricePix: 29.90,
    priceCard: 34.90,
    description: "Suporte compacto com ângulo otimizado para chamadas de vídeo e consumo de conteúdo no smartphone.",
    tags: ["celular", "acessório", "home office"],
    featured: false,
    readyToShip: true,
    stock: 20,
    dimensions: "8x7x9cm"
  },
  {
    id: "mdh-a1-004",
    sku: "MDH-A1-004",
    name: "Passa-Cabos Orbit",
    category: "Setup & Organização",
    collection: "A1 Mini Validada",
    material: "PETG",
    finish: "Standard",
    productionWindow: "24h",
    status: "Pronta entrega",
    grams: 30,
    hours: 1.2,
    complexity: 1.05,
    pricePix: 19.90,
    priceCard: 23.90,
    description: "Organizador de cabos robusto em PETG, ideal para gerenciar múltiplos fios na sua estação de trabalho.",
    tags: ["cabos", "organização", "petg"],
    featured: false,
    readyToShip: true,
    stock: 25,
    dimensions: "5x5x3cm"
  },
  {
    id: "mdh-a1-005",
    sku: "MDH-A1-005",
    name: "Organizador Desk Grid",
    category: "Setup & Organização",
    collection: "A1 Mini Validada",
    material: "PLA",
    finish: "Matte",
    productionWindow: "1-2 dias",
    status: "Sob encomenda",
    grams: 120,
    hours: 5.2,
    complexity: 1.3,
    pricePix: 89.90,
    priceCard: 99.90,
    description: "Sistema modular para organizar canetas, clips e pequenos acessórios de escritório com design moderno.",
    tags: ["escritório", "organização", "modular"],
    featured: true,
    readyToShip: false,
    stock: 5,
    dimensions: "15x15x4cm"
  },
  {
    id: "mdh-a1-006",
    sku: "MDH-A1-006",
    name: "Porta-Canetas Stack",
    category: "Setup & Organização",
    collection: "A1 Mini Validada",
    material: "PLA",
    finish: "Matte",
    productionWindow: "1-2 dias",
    status: "Sob encomenda",
    grams: 75,
    hours: 3.1,
    complexity: 1.2,
    pricePix: 45.90,
    priceCard: 52.90,
    description: "Porta-canetas com empilhamento otimizado e visual geométrico para destacar sua mesa.",
    tags: ["canetas", "geek", "geometria"],
    featured: false,
    readyToShip: false,
    stock: 12,
    dimensions: "8x8x10cm"
  },
  {
    id: "mdh-a1-007",
    sku: "MDH-A1-007",
    name: "Bandeja EDC Desk",
    category: "Setup & Organização",
    collection: "A1 Mini Validada",
    material: "PLA",
    finish: "Matte",
    productionWindow: "1-2 dias",
    status: "Sob encomenda",
    grams: 95,
    hours: 4.0,
    complexity: 1.25,
    pricePix: 59.90,
    priceCard: 68.90,
    description: "Bandeja para Every Day Carry (EDC): relógio, chaves, carteira e moedas em um só lugar.",
    tags: ["edc", "bandeja", "organização"],
    featured: false,
    readyToShip: false,
    stock: 8,
    dimensions: "18x12x2cm"
  },
  {
    id: "mdh-a1-008",
    sku: "MDH-A1-008",
    name: "Suporte Notebook Lift",
    category: "Setup & Organização",
    collection: "A1 Mini Validada",
    material: "PETG",
    finish: "Standard",
    productionWindow: "1-2 dias",
    status: "Sob encomenda",
    grams: 150,
    hours: 6.5,
    complexity: 1.4,
    pricePix: 99.90,
    priceCard: 114.90,
    description: "Pares de suportes robustos em PETG para elevar seu notebook, melhorando a ergonomia e o resfriamento.",
    tags: ["notebook", "ergonomia", "petg"],
    featured: true,
    readyToShip: false,
    stock: 6,
    dimensions: "20x5x5cm (par)"
  },
  {
    id: "mdh-a1-009",
    sku: "MDH-A1-009",
    name: "Vaso Geo Mini",
    category: "Casa & Decoração",
    collection: "Casa com Personalidade",
    material: "PLA",
    finish: "Silk",
    productionWindow: "24h",
    status: "Pronta entrega",
    grams: 40,
    hours: 1.8,
    complexity: 1.1,
    pricePix: 34.90,
    priceCard: 39.90,
    description: "Pequeno vaso geométrico com brilho seda (Silk), perfeito para suculentas e decoração minimalista.",
    tags: ["decoração", "vaso", "suculenta"],
    featured: true,
    readyToShip: true,
    stock: 18,
    dimensions: "8x8x7cm"
  },
  {
    id: "mdh-a1-010",
    sku: "MDH-A1-010",
    name: "Cachepot Prism",
    category: "Casa & Decoração",
    collection: "Casa com Personalidade",
    material: "PLA",
    finish: "Silk",
    productionWindow: "24h",
    status: "Pronta entrega",
    grams: 55,
    hours: 2.2,
    complexity: 1.15,
    pricePix: 45.90,
    priceCard: 52.90,
    description: "Cachepot com faces prismáticas que refletem a luz, ideal para dar vida a prateleiras e mesas.",
    tags: ["cachepot", "decoração", "brilho"],
    featured: false,
    readyToShip: true,
    stock: 14,
    dimensions: "10x10x9cm"
  },
  {
    id: "mdh-a1-011",
    sku: "MDH-A1-011",
    name: "Porta-Velas Halo",
    category: "Casa & Decoração",
    collection: "Casa com Personalidade",
    material: "PLA",
    finish: "Silk",
    productionWindow: "1-2 dias",
    status: "Sob encomenda",
    grams: 50,
    hours: 2.0,
    complexity: 1.2,
    pricePix: 39.90,
    priceCard: 45.90,
    description: "Suporte elegante para velas LED, criando um efeito de halo luminoso e ambiente aconchegante.",
    tags: ["velas", "iluminação", "aconchego"],
    featured: false,
    readyToShip: false,
    stock: 10,
    dimensions: "9x9x4cm"
  },
  {
    id: "mdh-a1-012",
    sku: "MDH-A1-012",
    name: "Porta-Chaves Wall Grid",
    category: "Casa & Decoração",
    collection: "Casa com Personalidade",
    material: "PETG",
    finish: "Standard",
    productionWindow: "1-2 dias",
    status: "Sob encomenda",
    grams: 60,
    hours: 2.5,
    complexity: 1.2,
    pricePix: 49.90,
    priceCard: 56.90,
    description: "Organizador de chaves de parede com design em grade, funcional e decorativo para o hall de entrada.",
    tags: ["chaves", "parede", "organização"],
    featured: false,
    readyToShip: false,
    stock: 8,
    dimensions: "15x5x2cm"
  },
  {
    id: "mdh-a1-013",
    sku: "MDH-A1-013",
    name: "Gancho Multi Hook",
    category: "Utilidades Reais",
    collection: "Funcionais do Dia a Dia",
    material: "PETG",
    finish: "Standard",
    productionWindow: "24h",
    status: "Pronta entrega",
    grams: 20,
    hours: 0.8,
    complexity: 1.0,
    pricePix: 14.90,
    priceCard: 17.90,
    description: "Gancho multiuso reforçado em PETG para pendurar mochilas, fones ou ferramentas.",
    tags: ["utilidade", "gancho", "resistente"],
    featured: false,
    readyToShip: true,
    stock: 40,
    dimensions: "4x4x6cm"
  },
  {
    id: "mdh-a1-014",
    sku: "MDH-A1-014",
    name: "Suporte Esponja Sink",
    category: "Utilidades Reais",
    collection: "Funcionais do Dia a Dia",
    material: "PETG",
    finish: "Standard",
    productionWindow: "24h",
    status: "Pronta entrega",
    grams: 25,
    hours: 1.1,
    complexity: 1.05,
    pricePix: 19.90,
    priceCard: 23.90,
    description: "Suporte de pia para esponja com drenagem eficiente, feito em PETG para maior durabilidade em áreas úmidas.",
    tags: ["cozinha", "pia", "utilidade"],
    featured: false,
    readyToShip: true,
    stock: 22,
    dimensions: "6x6x4cm"
  },
  {
    id: "mdh-a1-015",
    sku: "MDH-A1-015",
    name: "Organizador Gaveta Mini",
    category: "Utilidades Reais",
    collection: "Funcionais do Dia a Dia",
    material: "PLA",
    finish: "Matte",
    productionWindow: "1-2 dias",
    status: "Sob encomenda",
    grams: 55,
    hours: 2.4,
    complexity: 1.15,
    pricePix: 35.90,
    priceCard: 41.90,
    description: "Caixa organizadora pequena para gavetas, ideal para parafusos, bijuterias ou material de costura.",
    tags: ["gaveta", "organização", "caixa"],
    featured: false,
    readyToShip: false,
    stock: 15,
    dimensions: "10x10x4cm"
  },
  {
    id: "mdh-a1-016",
    sku: "MDH-A1-016",
    name: "Calço Porta Quiet",
    category: "Utilidades Reais",
    collection: "Funcionais do Dia a Dia",
    material: "TPU",
    finish: "Standard",
    productionWindow: "1-2 dias",
    status: "Sob encomenda",
    grams: 35,
    hours: 1.8,
    complexity: 1.3,
    pricePix: 29.90,
    priceCard: 34.90,
    description: "Calço de porta flexível em TPU, evita batidas e protege o piso com alta aderência.",
    tags: ["casa", "segurança", "flexível"],
    featured: false,
    readyToShip: false,
    stock: 12,
    dimensions: "10x3x3cm"
  },
  {
    id: "mdh-a1-017",
    sku: "MDH-A1-017",
    name: "Nome 3D Desk",
    category: "Presentes Criativos",
    collection: "Personalizados",
    material: "PLA",
    finish: "Silk",
    productionWindow: "24h",
    status: "Sob encomenda",
    grams: 60,
    hours: 2.5,
    complexity: 1.2,
    pricePix: 49.90,
    priceCard: 56.90,
    description: "Seu nome ou palavra favorita em 3D para decorar sua mesa com estilo e personalização única.",
    tags: ["personalizado", "nome", "presente"],
    featured: true,
    readyToShip: false,
    stock: 10,
    dimensions: "15x3x4cm (média)"
  },
  {
    id: "mdh-a1-018",
    sku: "MDH-A1-018",
    name: "Nome 3D Wall",
    category: "Presentes Criativos",
    collection: "Personalizados",
    material: "PLA",
    finish: "Silk",
    productionWindow: "1-2 dias",
    status: "Sob encomenda",
    grams: 80,
    hours: 3.5,
    complexity: 1.25,
    pricePix: 69.90,
    priceCard: 79.90,
    description: "Nomes em relevo para fixação em parede, ideais para quartos infantis e decoração comercial.",
    tags: ["parede", "decoração", "personalizado"],
    featured: false,
    readyToShip: false,
    stock: 8,
    dimensions: "25x5x1cm (média)"
  },
  {
    id: "mdh-a1-019",
    sku: "MDH-A1-019",
    name: "Placa Pix Premium",
    category: "Presentes Criativos",
    collection: "Personalizados",
    material: "PLA",
    finish: "Matte",
    productionWindow: "24h",
    status: "Sob encomenda",
    grams: 50,
    hours: 2.2,
    complexity: 1.2,
    pricePix: 45.90,
    priceCard: 52.90,
    description: "Expositor elegante para seu QR Code do Pix, facilitando pagamentos com um toque profissional.",
    tags: ["business", "pix", "comércio"],
    featured: true,
    readyToShip: false,
    stock: 15,
    dimensions: "10x5x12cm"
  },
  {
    id: "mdh-a1-020",
    sku: "MDH-A1-020",
    name: "Chaveiro Signature",
    category: "Presentes Criativos",
    collection: "Personalizados",
    material: "PLA",
    finish: "Standard",
    productionWindow: "24h",
    status: "Sob encomenda",
    grams: 10,
    hours: 0.5,
    complexity: 1.1,
    pricePix: 12.90,
    priceCard: 15.90,
    description: "Chaveiro personalizado com iniciais ou nomes curtos, um presente simples e marcante.",
    tags: ["chaveiro", "brinde", "personalizado"],
    featured: false,
    readyToShip: false,
    stock: 50,
    dimensions: "5x2x0.5cm"
  },
  {
    id: "mdh-a1-021",
    sku: "MDH-A1-021",
    name: "Topo de Bolo Layer",
    category: "Presentes Criativos",
    collection: "Personalizados",
    material: "PLA",
    finish: "Silk",
    productionWindow: "24h",
    status: "Sob encomenda",
    grams: 30,
    hours: 1.5,
    complexity: 1.2,
    pricePix: 39.90,
    priceCard: 45.90,
    description: "Topo de bolo personalizado em camadas, ideal para aniversários e eventos especiais.",
    tags: ["festa", "bolo", "celebração"],
    featured: false,
    readyToShip: false,
    stock: 20,
    dimensions: "15x15x0.3cm"
  },
  {
    id: "mdh-a1-022",
    sku: "MDH-A1-022",
    name: "Display QR Business",
    category: "Presentes Criativos",
    collection: "Personalizados",
    material: "PLA",
    finish: "Matte",
    productionWindow: "1-2 dias",
    status: "Sob encomenda",
    grams: 65,
    hours: 2.8,
    complexity: 1.25,
    pricePix: 59.90,
    priceCard: 68.90,
    description: "Display para balcão com múltiplos QR Codes (Instagram, Pix, WhatsApp) para seu negócio.",
    tags: ["marketing", "display", "business"],
    featured: false,
    readyToShip: false,
    stock: 10,
    dimensions: "15x8x12cm"
  },
  {
    id: "mdh-a1-023",
    sku: "MDH-A1-023",
    name: "Guardião Chibi",
    category: "Geek & Colecionáveis Autorais",
    collection: "Colecionáveis",
    material: "PLA",
    finish: "Matte",
    productionWindow: "1-2 dias",
    status: "Sob encomenda",
    grams: 45,
    hours: 2.4,
    complexity: 1.3,
    pricePix: 45.90,
    priceCard: 52.90,
    description: "Mascote autoral estilo Chibi, com acabamento fosco (Matte) e detalhes expressivos para sua estante.",
    tags: ["geek", "chibi", "autoral"],
    featured: true,
    readyToShip: false,
    stock: 12,
    dimensions: "7x6x8cm"
  },
  {
    id: "mdh-a1-024",
    sku: "MDH-A1-024",
    name: "Mecha Core Mini",
    category: "Geek & Colecionáveis Autorais",
    collection: "Colecionáveis",
    material: "PLA",
    finish: "Matte",
    productionWindow: "1-2 dias",
    status: "Sob encomenda",
    grams: 55,
    hours: 3.2,
    complexity: 1.4,
    pricePix: 59.90,
    priceCard: 68.90,
    description: "Miniatura inspirada em robôs Mecha, com design angular e visual técnico impressionante.",
    tags: ["mecha", "robô", "geek"],
    featured: false,
    readyToShip: false,
    stock: 10,
    dimensions: "9x7x11cm"
  },
  {
    id: "mdh-a1-025",
    sku: "MDH-A1-025",
    name: "Ninja Desk Bust",
    category: "Geek & Colecionáveis Autorais",
    collection: "Colecionáveis",
    material: "PLA",
    finish: "Matte",
    productionWindow: "1-2 dias",
    status: "Sob encomenda",
    grams: 70,
    hours: 3.8,
    complexity: 1.45,
    pricePix: 79.90,
    priceCard: 89.90,
    description: "Busto de ninja para mesa, capturando a essência do mistério e da habilidade em uma peça compacta.",
    tags: ["ninja", "busto", "display"],
    featured: true,
    readyToShip: false,
    stock: 8,
    dimensions: "10x8x12cm"
  },
  {
    id: "mdh-a1-026",
    sku: "MDH-A1-026",
    name: "Samurai Mask Stand",
    category: "Geek & Colecionáveis Autorais",
    collection: "Colecionáveis",
    material: "PLA",
    finish: "Matte",
    productionWindow: "2-4 dias",
    status: "Sob encomenda",
    grams: 110,
    hours: 5.5,
    complexity: 1.5,
    pricePix: 129.90,
    priceCard: 148.90,
    description: "Réplica estilizada de máscara samurai em suporte, uma peça de destaque para colecionadores exigentes.",
    tags: ["samurai", "máscara", "premium"],
    featured: true,
    readyToShip: false,
    stock: 5,
    dimensions: "12x12x18cm"
  },
  {
    id: "mdh-a1-027",
    sku: "MDH-A1-027",
    name: "Creature Flex",
    category: "Geek & Colecionáveis Autorais",
    collection: "Articulados",
    material: "PLA",
    finish: "Standard",
    productionWindow: "24h",
    status: "Pronta entrega",
    grams: 40,
    hours: 2.0,
    complexity: 1.25,
    pricePix: 39.90,
    priceCard: 45.90,
    description: "Criatura articulada impressa em uma única peça, divertida de manusear e perfeita para presentear.",
    tags: ["articulado", "fidget", "geek"],
    featured: false,
    readyToShip: true,
    stock: 20,
    dimensions: "15x5x3cm"
  },
  {
    id: "mdh-a1-028",
    sku: "MDH-A1-028",
    name: "Dragon Flex Mini",
    category: "Geek & Colecionáveis Autorais",
    collection: "Articulados",
    material: "PLA",
    finish: "Standard",
    productionWindow: "24h",
    status: "Pronta entrega",
    grams: 35,
    hours: 1.8,
    complexity: 1.3,
    pricePix: 45.90,
    priceCard: 52.90,
    description: "Mini dragão articulado com movimento fluido, uma das peças mais populares da impressão 3D.",
    tags: ["dragão", "articulado", "coleção"],
    featured: true,
    readyToShip: true,
    stock: 15,
    dimensions: "12x4x3cm"
  },
  {
    id: "mdh-a1-029",
    sku: "MDH-A1-029",
    name: "Serpente Flex",
    category: "Geek & Colecionáveis Autorais",
    collection: "Articulados",
    material: "PLA",
    finish: "Standard",
    productionWindow: "1-2 dias",
    status: "Sob encomenda",
    grams: 50,
    hours: 2.5,
    complexity: 1.25,
    pricePix: 49.90,
    priceCard: 56.90,
    description: "Serpente articulada longa com movimento realista, ideal para quem gosta de itens tácteis e dinâmicos.",
    tags: ["serpente", "flexível", "fidget"],
    featured: false,
    readyToShip: false,
    stock: 12,
    dimensions: "25x2x2cm"
  },
  {
    id: "mdh-a1-030",
    sku: "MDH-A1-030",
    name: "Robot Dummy Desk",
    category: "Geek & Colecionáveis Autorais",
    collection: "Articulados",
    material: "PLA",
    finish: "Standard",
    productionWindow: "1-2 dias",
    status: "Sob encomenda",
    grams: 45,
    hours: 2.2,
    complexity: 1.35,
    pricePix: 55.90,
    priceCard: 63.90,
    description: "Boneco robô totalmente articulado para posar em sua mesa, ótimo para referências artísticas ou diversão.",
    tags: ["robô", "articulado", "posável"],
    featured: false,
    readyToShip: false,
    stock: 10,
    dimensions: "12x5x2cm"
  },
  {
    id: "mdh-a1-031",
    sku: "MDH-A1-031",
    name: "Placa Gamer Neon Frame",
    category: "Setup & Organização",
    collection: "Setup Premium",
    material: "PLA",
    finish: "Silk",
    productionWindow: "1-2 dias",
    status: "Sob encomenda",
    grams: 90,
    hours: 4.5,
    complexity: 1.35,
    pricePix: 89.90,
    priceCard: 99.90,
    description: "Placa decorativa com visual inspirado em neon, perfeita para gamers e streamers destacarem seu espaço.",
    tags: ["gamer", "setup", "decoração"],
    featured: true,
    readyToShip: false,
    stock: 8,
    dimensions: "20x10x2cm"
  },
  {
    id: "mdh-a1-032",
    sku: "MDH-A1-032",
    name: "Dock Stream Deck Mini",
    category: "Setup & Organização",
    collection: "Setup Premium",
    material: "PLA",
    finish: "Matte",
    productionWindow: "1-2 dias",
    status: "Sob encomenda",
    grams: 50,
    hours: 2.5,
    complexity: 1.2,
    pricePix: 59.90,
    priceCard: 68.90,
    description: "Suporte angulado para Stream Deck ou macro pads, melhorando o acesso e a visibilidade dos comandos.",
    tags: ["streamer", "setup", "produtividade"],
    featured: false,
    readyToShip: false,
    stock: 12,
    dimensions: "10x8x7cm"
  },
  {
    id: "mdh-a1-033",
    sku: "MDH-A1-033",
    name: "Suporte Webcam Angle",
    category: "Setup & Organização",
    collection: "Setup Premium",
    material: "PLA",
    finish: "Matte",
    productionWindow: "24h",
    status: "Sob encomenda",
    grams: 35,
    hours: 1.8,
    complexity: 1.15,
    pricePix: 39.90,
    priceCard: 45.90,
    description: "Suporte de webcam para topo de monitor ou prateleira, com ajuste fino de inclinação.",
    tags: ["webcam", "videochamada", "setup"],
    featured: false,
    readyToShip: false,
    stock: 15,
    dimensions: "6x5x8cm"
  },
  {
    id: "mdh-a1-034",
    sku: "MDH-A1-034",
    name: "Base Controle Duo",
    category: "Setup & Organização",
    collection: "Setup Premium",
    material: "PLA",
    finish: "Matte",
    productionWindow: "1-2 dias",
    status: "Sob encomenda",
    grams: 110,
    hours: 5.0,
    complexity: 1.3,
    pricePix: 89.90,
    priceCard: 99.90,
    description: "Suporte duplo para dois controles de console, economizando espaço e mantendo tudo pronto para o player 2.",
    tags: ["gaming", "setup", "controles"],
    featured: false,
    readyToShip: false,
    stock: 10,
    dimensions: "15x10x12cm"
  },
  {
    id: "mdh-a1-035",
    sku: "MDH-A1-035",
    name: "Tag Pet Bone",
    category: "PET / Casa",
    collection: "Pet",
    material: "PLA",
    finish: "Standard",
    productionWindow: "24h",
    status: "Sob encomenda",
    grams: 10,
    hours: 0.6,
    complexity: 1.1,
    pricePix: 19.90,
    priceCard: 22.90,
    description: "Plaquinha de identificação para pet em formato de osso, personalizada com nome e telefone.",
    tags: ["pet", "identificação", "cachorro"],
    featured: false,
    readyToShip: false,
    stock: 30,
    dimensions: "4x2.5x0.3cm"
  },
  {
    id: "mdh-a1-036",
    sku: "MDH-A1-036",
    name: "Porta-Saquinho Walk",
    category: "PET / Casa",
    collection: "Pet",
    material: "PETG",
    finish: "Standard",
    productionWindow: "24h",
    status: "Sob encomenda",
    grams: 30,
    hours: 1.5,
    complexity: 1.2,
    pricePix: 29.90,
    priceCard: 34.90,
    description: "Dispensador de saquinhos higiênicos para passeio, resistente e prático para prender na guia.",
    tags: ["pet", "passeio", "higiene"],
    featured: false,
    readyToShip: false,
    stock: 20,
    dimensions: "8x4x4cm"
  },
  {
    id: "mdh-a1-037",
    sku: "MDH-A1-037",
    name: "Suporte Guia Wall",
    category: "PET / Casa",
    collection: "Pet",
    material: "PETG",
    finish: "Standard",
    productionWindow: "1-2 dias",
    status: "Sob encomenda",
    grams: 40,
    hours: 1.9,
    complexity: 1.2,
    pricePix: 39.90,
    priceCard: 45.90,
    description: "Suporte de parede para organizar guias e coleiras do seu pet, mantendo a entrada da casa organizada.",
    tags: ["pet", "parede", "organização"],
    featured: false,
    readyToShip: false,
    stock: 15,
    dimensions: "10x5x3cm"
  },
  {
    id: "mdh-a1-038",
    sku: "MDH-A1-038",
    name: "Plaquinha Pet Home",
    category: "PET / Casa",
    collection: "Pet",
    material: "PLA",
    finish: "Matte",
    productionWindow: "1-2 dias",
    status: "Sob encomenda",
    grams: 25,
    hours: 1.2,
    complexity: 1.15,
    pricePix: 34.90,
    priceCard: 39.90,
    description: "Plaquinha decorativa para a casa do pet ou cantinho da ração, personalizada com o nome.",
    tags: ["pet", "decoração", "casa"],
    featured: false,
    readyToShip: false,
    stock: 18,
    dimensions: "12x8x0.5cm"
  },
  {
    id: "mdh-a1-039",
    sku: "MDH-A1-039",
    name: "Vela LED Shell",
    category: "Casa & Decoração",
    collection: "Casa com Personalidade",
    material: "PLA",
    finish: "Silk",
    productionWindow: "1-2 dias",
    status: "Sob encomenda",
    grams: 45,
    hours: 2.1,
    complexity: 1.2,
    pricePix: 49.90,
    priceCard: 56.90,
    description: "Suporte para vela LED em formato de concha, perfeito para decoração temática e relaxamento.",
    tags: ["decoração", "velas", "concha"],
    featured: false,
    readyToShip: false,
    stock: 12,
    dimensions: "10x10x6cm"
  },
  {
    id: "mdh-a1-040",
    sku: "MDH-A1-040",
    name: "Luminária Orb Mini",
    category: "Casa & Decoração",
    collection: "Casa com Personalidade",
    material: "PLA",
    finish: "Silk",
    productionWindow: "2-4 dias",
    status: "Sob encomenda",
    grams: 120,
    hours: 6.0,
    complexity: 1.4,
    pricePix: 149.90,
    priceCard: 169.90,
    description: "Luminária esférica minimalista para lâmpadas LED, criando uma iluminação difusa e charmosa.",
    tags: ["luminária", "decoração", "premium"],
    featured: true,
    readyToShip: false,
    stock: 5,
    dimensions: "15x15x15cm"
  },
  {
    id: "mdh-a1-041",
    sku: "MDH-A1-041",
    name: "Escultura Spiral Mini",
    category: "Casa & Decoração",
    collection: "Casa com Personalidade",
    material: "PLA",
    finish: "Silk",
    productionWindow: "2-4 dias",
    status: "Sob encomenda",
    grams: 80,
    hours: 4.5,
    complexity: 1.35,
    pricePix: 89.90,
    priceCard: 99.90,
    description: "Escultura decorativa com formas espiraladas complexas, uma demonstração da arte em 3D.",
    tags: ["escultura", "arte", "decoração"],
    featured: false,
    readyToShip: false,
    stock: 8,
    dimensions: "10x10x15cm"
  },
  {
    id: "mdh-a1-042",
    sku: "MDH-A1-042",
    name: "Busto Hero Autoral",
    category: "Geek & Colecionáveis Autorais",
    collection: "Colecionáveis",
    material: "PLA",
    finish: "Matte",
    productionWindow: "2-4 dias",
    status: "Sob encomenda",
    grams: 130,
    hours: 7.2,
    complexity: 1.5,
    pricePix: 189.90,
    priceCard: 214.90,
    description: "Busto heróico autoral com nível máximo de detalhes, ideal para pintura ou exibição premium.",
    tags: ["geek", "busto", "colecionador"],
    featured: true,
    readyToShip: false,
    stock: 4,
    dimensions: "15x10x18cm"
  },
  {
    id: "mdh-a1-043",
    sku: "MDH-a1-043",
    name: "Brinde Corporativo Mini",
    category: "Presentes Criativos",
    collection: "Personalizados",
    material: "PLA",
    finish: "Standard",
    productionWindow: "2-4 dias",
    status: "Sob encomenda",
    grams: 15,
    hours: 0.8,
    complexity: 1.1,
    pricePix: 15.90,
    priceCard: 18.90,
    description: "Opção de brinde personalizado para empresas, eventos e lembranças em quantidade.",
    tags: ["corporativo", "brinde", "lote"],
    featured: false,
    readyToShip: false,
    stock: 100,
    dimensions: "5x5x5cm (base)"
  },
  {
    id: "mdh-a1-044",
    sku: "MDH-a1-044",
    name: "Troféu Layer Award",
    category: "Presentes Criativos",
    collection: "Personalizados",
    material: "PLA",
    finish: "Silk",
    productionWindow: "2-4 dias",
    status: "Sob encomenda",
    grams: 100,
    hours: 5.5,
    complexity: 1.4,
    pricePix: 129.90,
    priceCard: 148.90,
    description: "Troféu personalizado com design em camadas, perfeito para premiações e reconhecimento de mérito.",
    tags: ["troféu", "prêmio", "personalizado"],
    featured: false,
    readyToShip: false,
    stock: 5,
    dimensions: "10x10x20cm"
  },
  {
    id: "mdh-a1-045",
    sku: "MDH-A1-045",
    name: "Peça Sob Medida Compact",
    category: "Sob Encomenda",
    collection: "Projetos Específicos",
    material: "PLA",
    finish: "Conforme briefing",
    productionWindow: "2-4 dias",
    status: "Sob encomenda",
    grams: 50,
    hours: 3.0,
    complexity: 1.3,
    pricePix: 49.90,
    priceCard: 56.90,
    description: "Item base para projetos sob medida compactos. Envie seu arquivo ou ideia para orçamento final.",
    tags: ["encomenda", "personalizado", "sob medida"],
    featured: true,
    readyToShip: false,
    stock: 0,
    dimensions: "Variável"
  },
  {
    id: "mdh-a1-046",
    sku: "MDH-A1-046",
    name: "Peça Sob Medida Funcional",
    category: "Sob Encomenda",
    collection: "Projetos Específicos",
    material: "PETG",
    finish: "Conforme briefing",
    productionWindow: "2-4 dias",
    status: "Sob encomenda",
    grams: 100,
    hours: 5.0,
    complexity: 1.4,
    pricePix: 89.90,
    priceCard: 99.90,
    description: "Item base para projetos funcionais e técnicos sob medida em PETG resistente.",
    tags: ["técnico", "funcional", "petg"],
    featured: false,
    readyToShip: false,
    stock: 0,
    dimensions: "Variável"
  },
  {
    id: "mdh-a1-047",
    sku: "MDH-A1-047",
    name: "Reposição Plástica Técnica",
    category: "Sob Encomenda",
    collection: "Projetos Específicos",
    material: "PETG",
    finish: "Standard",
    productionWindow: "2-4 dias",
    status: "Sob encomenda",
    grams: 80,
    hours: 4.5,
    complexity: 1.4,
    pricePix: 79.90,
    priceCard: 89.90,
    description: "Criação de peças de reposição que não existem mais no mercado, usando engenharia reversa simples.",
    tags: ["reposição", "manutenção", "técnico"],
    featured: false,
    readyToShip: false,
    stock: 0,
    dimensions: "Variável"
  },
  {
    id: "mdh-a1-048",
    sku: "MDH-A1-048",
    name: "Projeto Personalizado A1",
    category: "Sob Encomenda",
    collection: "Projetos Específicos",
    material: "Conforme briefing",
    finish: "Conforme briefing",
    productionWindow: "2-4 dias",
    status: "Sob encomenda",
    grams: 200,
    hours: 10.0,
    complexity: 1.5,
    pricePix: 199.90,
    priceCard: 228.90,
    description: "Projeto completo de modelagem e impressão 3D para necessidades complexas e exclusivas.",
    tags: ["projeto", "completo", "exclusivo"],
    featured: true,
    readyToShip: false,
    stock: 0,
    dimensions: "Variável"
  }
];
