import type { Product } from "@/lib/catalog";

export const verifiedCatalog: Product[] = [
  {
    id: "real-001",
    sku: "REAL-0001",
    name: "Grinder 3 Partes Premium",
    category: "Utilidades Reais",
    subcategory: "Acessório",
    theme: "uso pessoal",
    collection: "Projetos reais",
    colors: ["Preto"],
    grams: 92,
    hours: 3.8,
    complexity: 1.46,
    featured: true,
    description: "Grinder impresso em 3D com duas metades de encaixe, dentes internos e proposta funcional para uso pessoal ou presente criativo.",
    tags: ["grinder", "acessório", "foto real", "projeto real"],
    price: 54.9,
    printTime: "3.8h",
    plaWeight: "92g",
    dimensions: "7x7x4cm",
    images: [
      "/products/foto-001-grinder-01.webp",
      "/products/foto-002-grinder-02.webp",
      "/products/render-real-001-grinder.webp"
    ],
    licenseType: "personal",
    variants: [{ color: "Preto", available: true }],
    pricePix: 54.9,
    priceCard: 61.9,
    marketplaceSuggested: 68.9,
    productionWindow: "2 a 4 dias",
    imageHint: "Grinder 3 Partes Premium",
    image: "/products/foto-001-grinder-01.webp",
    material: "PLA Premium",
    finish: "Fosco",
    status: "Sob encomenda",
    stock: 3,
    customizable: true,
    readyToShip: false,
  },
  {
    id: "real-002",
    sku: "REAL-0002",
    name: "Porta Creme Dental de Bancada",
    category: "Utilidades Reais",
    subcategory: "Organizador",
    theme: "banheiro",
    collection: "Projetos reais",
    colors: ["Preto"],
    grams: 58,
    hours: 2.7,
    complexity: 1.34,
    featured: true,
    description: "Suporte compacto para tubo de creme dental com base estável, pensado para banheiro, bancada ou kit de higiene personalizado.",
    tags: ["banheiro", "organizador", "foto real", "projeto real"],
    price: 39.9,
    printTime: "2.7h",
    plaWeight: "58g",
    dimensions: "8x6x7cm",
    images: [
      "/products/foto-003-porta-creme-dental.webp",
      "/products/render-real-002-porta-creme.webp"
    ],
    licenseType: "personal",
    variants: [{ color: "Preto", available: true }],
    pricePix: 39.9,
    priceCard: 45.9,
    marketplaceSuggested: 51.9,
    productionWindow: "2 a 4 dias",
    imageHint: "Porta Creme Dental de Bancada",
    image: "/products/foto-003-porta-creme-dental.webp",
    material: "PLA Premium",
    finish: "Fosco",
    status: "Sob encomenda",
    stock: 4,
    customizable: true,
    readyToShip: false,
  },
  {
    id: "real-003",
    sku: "REAL-0003",
    name: "Demogorgon Decorativo Premium",
    category: "Geek & Colecionáveis",
    subcategory: "Miniatura",
    theme: "terror sci-fi",
    collection: "Projetos reais",
    colors: ["Vermelho", "Marrom"],
    grams: 148,
    hours: 7.4,
    complexity: 1.72,
    featured: true,
    description: "Miniatura inspirada em criatura sci-fi com pose de destaque, pintura temática e apelo forte para decoração geek e coleção.",
    tags: ["demogorgon", "terror", "colecionável", "foto real"],
    price: 129.9,
    printTime: "7.4h",
    plaWeight: "148g",
    dimensions: "16x10x23cm",
    images: [
      "/products/foto-004-demogorgon.webp",
      "/products/render-real-003-demogorgon.webp"
    ],
    licenseType: "personal",
    variants: [{ color: "Pintura temática", available: true }],
    pricePix: 129.9,
    priceCard: 146.9,
    marketplaceSuggested: 162.9,
    productionWindow: "4 a 7 dias",
    imageHint: "Demogorgon Decorativo Premium",
    image: "/products/foto-004-demogorgon.webp",
    material: "PLA Premium",
    finish: "Pintado à mão",
    status: "Sob encomenda",
    stock: 1,
    customizable: true,
    readyToShip: false,
  },
  {
    id: "real-004",
    sku: "REAL-0004",
    name: "Hello Kitty Jedi Colecionável",
    category: "Geek & Colecionáveis",
    subcategory: "Chibi",
    theme: "kawaii sci-fi",
    collection: "Projetos reais",
    colors: ["Branco", "Rosa", "Marrom"],
    grams: 76,
    hours: 4.2,
    complexity: 1.52,
    featured: true,
    description: "Peça de coleção com mistura kawaii e sci-fi, base cenográfica e acabamento pensado para presente geek de alto impacto visual.",
    tags: ["hello kitty", "colecionável", "fan art", "foto real"],
    price: 89.9,
    printTime: "4.2h",
    plaWeight: "76g",
    dimensions: "10x8x15cm",
    images: [
      "/products/foto-005-hello-kitty-jedi.webp",
      "/products/render-real-004-hello-kitty-jedi.webp"
    ],
    licenseType: "personal",
    variants: [{ color: "Temática", available: true }],
    pricePix: 89.9,
    priceCard: 101.9,
    marketplaceSuggested: 113.9,
    productionWindow: "3 a 6 dias",
    imageHint: "Hello Kitty Jedi Colecionável",
    image: "/products/foto-005-hello-kitty-jedi.webp",
    material: "PLA Premium",
    finish: "Pintado à mão",
    status: "Sob encomenda",
    stock: 1,
    customizable: true,
    readyToShip: false,
  },
  {
    id: "real-005",
    sku: "REAL-0005",
    name: "Stencil Rick and Morty Decorativo",
    category: "Casa & Decoração",
    subcategory: "Quadro",
    theme: "cartoon sci-fi",
    collection: "Projetos reais",
    colors: ["Preto"],
    grams: 44,
    hours: 2.2,
    complexity: 1.26,
    featured: false,
    description: "Stencil decorativo para parede, luminária ou moldura, com recorte inspirado em cartoon sci-fi e composição forte para setup geek.",
    tags: ["stencil", "quadro", "rick and morty", "foto real"],
    price: 42.9,
    printTime: "2.2h",
    plaWeight: "44g",
    dimensions: "18x18x1cm",
    images: [
      "/products/foto-006-stencil-rick-morty.webp",
      "/products/render-real-005-stencil.webp"
    ],
    licenseType: "personal",
    variants: [{ color: "Preto", available: true }],
    pricePix: 42.9,
    priceCard: 48.9,
    marketplaceSuggested: 54.9,
    productionWindow: "2 a 4 dias",
    imageHint: "Stencil Rick and Morty Decorativo",
    image: "/products/foto-006-stencil-rick-morty.webp",
    material: "PLA Premium",
    finish: "Fosco",
    status: "Sob encomenda",
    stock: 2,
    customizable: true,
    readyToShip: false,
  },
  {
    id: "real-006",
    sku: "REAL-0006",
    name: "Família Customizada em Miniatura",
    category: "Presentes Criativos",
    subcategory: "Escultura",
    theme: "família personalizada",
    collection: "Projetos reais",
    colors: ["Colorido"],
    grams: 168,
    hours: 9.5,
    complexity: 1.84,
    featured: true,
    description: "Miniatura personalizada de família com base expositora, feita sob briefing, fotos e preferências do cliente para presente afetivo.",
    tags: ["família", "personalizado", "presente", "foto real"],
    price: 189.9,
    printTime: "9.5h",
    plaWeight: "168g",
    dimensions: "14x10x19cm",
    images: [
      "/products/foto-007-familia-custom.webp",
      "/products/render-real-006-familia-custom.webp"
    ],
    licenseType: "personal",
    variants: [{ color: "Colorido", available: true }],
    pricePix: 189.9,
    priceCard: 214.9,
    marketplaceSuggested: 238.9,
    productionWindow: "5 a 10 dias",
    imageHint: "Família Customizada em Miniatura",
    image: "/products/foto-007-familia-custom.webp",
    material: "PLA Premium",
    finish: "Pintado à mão",
    status: "Sob encomenda",
    stock: 1,
    customizable: true,
    readyToShip: false,
  },
  {
    id: "real-007",
    sku: "REAL-0007",
    name: "Boneca Infantil Personalizada",
    category: "Presentes Criativos",
    subcategory: "Escultura",
    theme: "boneca personalizada",
    collection: "Projetos reais",
    colors: ["Rosa", "Marrom", "Colorido"],
    grams: 94,
    hours: 5.4,
    complexity: 1.64,
    featured: false,
    description: "Boneca infantil em estilo chibi com base decorada e visual afetivo, ideal para lembrança, decoração ou presente personalizado.",
    tags: ["boneca", "infantil", "personalizado", "foto real"],
    price: 96.9,
    printTime: "5.4h",
    plaWeight: "94g",
    dimensions: "10x8x16cm",
    images: [
      "/products/foto-008-boneca-crianca.webp",
      "/products/render-real-007-boneca-crianca.webp"
    ],
    licenseType: "personal",
    variants: [{ color: "Colorido", available: true }],
    pricePix: 96.9,
    priceCard: 109.9,
    marketplaceSuggested: 121.9,
    productionWindow: "4 a 7 dias",
    imageHint: "Boneca Infantil Personalizada",
    image: "/products/foto-008-boneca-crianca.webp",
    material: "PLA Premium",
    finish: "Pintado à mão",
    status: "Sob encomenda",
    stock: 1,
    customizable: true,
    readyToShip: false,
  },
  {
    id: "real-008",
    sku: "REAL-0008",
    name: "Case de Isqueiro Caveira",
    category: "Utilidades Reais",
    subcategory: "Acessório",
    theme: "caveira",
    collection: "Projetos reais",
    colors: ["Preto"],
    grams: 36,
    hours: 1.9,
    complexity: 1.29,
    featured: false,
    description: "Case para isqueiro com textura cilíndrica e relevo de caveira, pensado como acessório de bolso com personalidade visual.",
    tags: ["isqueiro", "case", "caveira", "foto real"],
    price: 34.9,
    printTime: "1.9h",
    plaWeight: "36g",
    dimensions: "3x3x8cm",
    images: [
      "/products/foto-009-case-isqueiro-caveira.webp",
      "/products/render-real-008-case-isqueiro.webp"
    ],
    licenseType: "personal",
    variants: [{ color: "Preto", available: true }],
    pricePix: 34.9,
    priceCard: 39.9,
    marketplaceSuggested: 44.9,
    productionWindow: "2 a 4 dias",
    imageHint: "Case de Isqueiro Caveira",
    image: "/products/foto-009-case-isqueiro-caveira.webp",
    material: "PLA Premium",
    finish: "Fosco",
    status: "Sob encomenda",
    stock: 5,
    customizable: true,
    readyToShip: false,
  },
  {
    id: "real-009",
    sku: "REAL-0009",
    name: "Homer Pikachu Mashup Colecionável",
    category: "Geek & Colecionáveis",
    subcategory: "Miniatura",
    theme: "mashup cartoon",
    collection: "Projetos reais",
    colors: ["Amarelo", "Rosa"],
    grams: 88,
    hours: 4.8,
    complexity: 1.58,
    featured: false,
    description: "Miniatura mashup com humor visual e cenário de bancada, criada para fãs de cultura pop, coleção de nicho e presentes divertidos.",
    tags: ["mashup", "cartoon", "colecionável", "foto real"],
    price: 82.9,
    printTime: "4.8h",
    plaWeight: "88g",
    dimensions: "9x8x16cm",
    images: [
      "/products/foto-010-homer-pikachu.webp",
      "/products/render-real-009-homer-pikachu.webp"
    ],
    licenseType: "personal",
    variants: [{ color: "Colorido", available: true }],
    pricePix: 82.9,
    priceCard: 93.9,
    marketplaceSuggested: 104.9,
    productionWindow: "4 a 7 dias",
    imageHint: "Homer Pikachu Mashup Colecionável",
    image: "/products/foto-010-homer-pikachu.webp",
    material: "PLA Premium",
    finish: "Pintado à mão",
    status: "Sob encomenda",
    stock: 1,
    customizable: true,
    readyToShip: false,
  },
  {
    id: "real-010",
    sku: "REAL-0010",
    name: "Medalha Maçônica Personalizada",
    category: "Presentes Criativos",
    subcategory: "Chaveiro",
    theme: "símbolo institucional",
    collection: "Projetos reais",
    colors: ["Preto", "Azul", "Dourado"],
    grams: 42,
    hours: 2.4,
    complexity: 1.38,
    featured: true,
    description: "Medalha ou chaveiro institucional com texto, símbolo e argola metálica, ideal para presentes, eventos ou encomendas por lote.",
    tags: ["maçonaria", "medalha", "chaveiro", "foto real"],
    price: 37.9,
    printTime: "2.4h",
    plaWeight: "42g",
    dimensions: "6x6x0.8cm",
    images: [
      "/products/foto-011-chaveiro-maconaria.webp",
      "/products/render-real-010-chaveiro-maconaria.webp"
    ],
    licenseType: "personal",
    variants: [{ color: "Colorido", available: true }],
    pricePix: 37.9,
    priceCard: 42.9,
    marketplaceSuggested: 47.9,
    productionWindow: "2 a 5 dias",
    imageHint: "Medalha Maçônica Personalizada",
    image: "/products/foto-011-chaveiro-maconaria.webp",
    material: "PLA Premium",
    finish: "Colorido",
    status: "Sob encomenda",
    stock: 8,
    customizable: true,
    readyToShip: false,
  },
];
